### ISSUE TITLE
火箭人射手 在12的手机闪退

### ISSUE THREAD

**Issue by h923745834** [FBlackBox/BlackBox#106]
在系统12的谷歌手机上（其他机型没试过），克隆这款游戏可以正常运行，但如果是通过apk包安装的，就会闪退。

apk包地址  https://github.com/h923745834/testApk.git

报错日志：
2022-04-14 17:49:20.849 18055-18091/com.cqwx.hcrss.meta E/AndroidRuntime: FATAL EXCEPTION: Thread-7
    Process: com.cqwx.hcrss.meta, PID: 18055
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:108)
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:93)
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:105)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user/0/top.niunaijun.blackboxa32/blackbox/data/app/com.cqwx.hcrss.meta/base.apk"],nativeLibraryDirectories=[/data/user/0/top.niunaijun.blackboxa32/blackbox/data/app/com.cqwx.hcrss.meta/lib, /data/user/0/top.niunaijun.blackboxa32/blackbox/data/app/com.cqwx.hcrss.meta/base.apk!/lib/armeabi-v7a, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.android.volley.toolbox.HurlStack.performRequest(HurlStack.java:108) 
        at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:93) 
        at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:105)

**Comment by CarryFan** [comment]
老哥，解决了吗，我也遇到问题了

**Comment by h923745834** [comment]
还没解决。10的系统是可以apk包安装的运行的。




保持一颗童心，追逐心中的梦。永不言败，希望在手中。


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FBlackBox/BlackBox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月16日(星期一) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FBlackBox/BlackBox] 火箭人射手 在12的手机闪退 (Issue #106)





 
老哥，解决了吗，我也遇到问题了
