### ISSUE TITLE
[BUG] 哔哩哔哩 安卓12崩溃

### ISSUE THREAD

**Issue by Mubai-meng** [FBlackBox/BlackBox#115]
安装哔哩哔哩后可以打开，几秒后弹出应用
异常并闪退（无论是否开启xp功能）

三星 one ui 4.1
安卓12

**Logcat** / **日志**
This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: top.niunaijun.blackboxa64:p0
PID: 17161
UID: 10457
Flags: 0x30c8be44
Package: top.niunaijun.blackboxa64 v12 (2.1.0)
Foreground: No
Process-Runtime: 84259984
Build: samsung/o1qzcx/o1q:12/SP1A.210812.016/G9910ZCS2CVCB:user/release-keys
Loading-Progress: 1.0

java.lang.RuntimeException: Unable to start service top.niunaijun.blackbox.proxy.ProxyService$P0@5be2774 with Intent { act=0b8f6d8f-8fc7-43cf-b716-5b2eb046b168 cmp=top.niunaijun.blackboxa64/top.niunaijun.blackbox.proxy.ProxyService$P0 (has extras) }: java.lang.RuntimeException: Unable to makeApplication
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
	at android.app.ActivityThread.access$2200(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.RuntimeException: Unable to makeApplication
	at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:382)
	at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:293)
	at top.niunaijun.blackbox.app.BActivityThread.createService(BActivityThread.java:207)
	at top.niunaijun.blackbox.app.dispatcher.AppServiceDispatcher.getOrCreateService(AppServiceDispatcher.java:232)
	at top.niunaijun.blackbox.app.dispatcher.AppServiceDispatcher.onStartCommand(AppServiceDispatcher.java:85)
	at top.niunaijun.blackbox.proxy.ProxyService.onStartCommand(ProxyService.java:34)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
	... 9 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
	at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
	at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:376)
	... 15 more

This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: top.niunaijun.blackboxa64:p1
PID: 7726
UID: 10457
Flags: 0x30c8be44
Package: top.niunaijun.blackboxa64 v12 (2.1.0)
Foreground: No
Process-Runtime: 84306987
Build: samsung/o1qzcx/o1q:12/SP1A.210812.016/G9910ZCS2CVCB:user/release-keys
Loading-Progress: 1.0

----- Output from /proc/pressure/memory -----
some avg10=0.00 avg60=0.31 avg300=0.35 total=56815722
full avg10=0.00 avg60=0.14 avg300=0.17 total=33163157
----- End output from /proc/pressure/memory -----

CPU usage from 12653ms to 0ms ago (2022-04-21 11:44:52.119 to 2022-04-21 11:45:04.773):
  99% 6698/top.niunaijun.blackboxa64:black: 99% user + 0% kernel
  18% 1290/system_server: 10% user + 8.6% kernel / faults: 24789 minor
  9.2% 1169/surfaceflinger: 6.1% user + 3% kernel / faults: 292 minor
  7.3% 3018/com.sec.android.app.launcher: 4.7% user + 2.6% kernel / faults: 5791 minor 1 major
  5.1% 7849/top.niunaijun.blackboxa64: 3.4% user + 1.6% kernel / faults: 13200 minor
  3.3% 1087/vendor.qti.hardware.display.composer-service: 2% user + 1.2% kernel / faults: 85 minor
  3.3% 2456/com.android.systemui: 2.4% user + 0.8% kernel / faults: 3804 minor 9 major
  2.7% 421/crtc_commit:142: 0% user + 2.7% kernel
  2.4% 14021/kworker/u16:9-ufs_clkscaling_0: 0% user + 2.4% kernel
  2.3% 671/logd: 0.7% user + 1.5% kernel / faults: 611 minor 56 major
  2.2% 24400/kworker/u16:2-ufs_clkscaling_0: 0% user + 2.2% kernel
  1.1% 14016/kworker/u16:3-ufs_clkscaling_0: 0% user + 1.1% kernel
  1% 648/dhd_rpm_state_t: 0% user + 1% kernel
  0.7% 1059/android.hardware.sensors@2.0-service.multihal: 0.4% user + 0.3% kernel / faults: 20 minor
  0.6% 12/rcuog/0: 0% user + 0.6% kernel
  0.6% 5013/com.sec.android.sdhms: 0.4% user + 0.1% kernel / faults: 346 minor
  0.6% 8041/org.kustom.widget: 0.3% user + 0.3% kernel / faults: 454 minor 10 major
  0.6% 24283/kworker/u16:1-devfreq_wq: 0% user + 0.6% kernel
  0.5% 188/kgsl_worker_thr: 0% user + 0.5% kernel
  0.5% 3672/kworker/3:1-events: 0% user + 0.5% kernel
  0.4% 1069/vendor.samsung.hardware.hyper-service: 0% user + 0.4% kernel / faults: 117 minor
  0.4% 1072/android.hardware.power.samsung-service: 0% user + 0.4% kernel
  0.4% 1097/vendor.qti.hardware.perf@2.2-service: 0.1% user + 0.3% kernel / faults: 33 minor
  0.3% 11/rcu_preempt: 0% user + 0.3% kernel
  0.3% 138/system: 0% user + 0.3% kernel
  0.3% 422/crtc_event:142: 0% user + 0.3% kernel
  0.3% 1085/vendor.qti.hardware.display.allocator-service: 0% user + 0.3% kernel / faults: 88 minor
  0.3% 2426/com.android.phone: 0% user + 0.2% kernel / faults: 55 minor 1 major
  0.3% 3473/argosd: 0% user + 0.2% kernel
  0.2% 39/rcuog/4: 0% user + 0.2% kernel
  0.2% 166/kzerod: 0% user + 0.2% kernel
  0.2% 672/lmkd: 0% user + 0.1% kernel
  0.2% 673/servicemanager: 0% user + 0.1% kernel
  0.2% 930/statsd: 0.1% user + 0% kernel / faults: 15 minor 1 major
  0.1% 13/rcuop/0: 0% user + 0.1% kernel
  0.1% 21/rcuop/1: 0% user + 0.1% kernel
  0.1% 644/irq/387-slsi_ts: 0% user + 0.1% kernel
  0.1% 733/iod: 0% user + 0% kernel
  0.1% 1061/android.hardware.wifi@1.0-service: 0% user + 0% kernel
  0.1% 1544/wificond: 0% user + 0.1% kernel
  0.1% 5329/com.samsung.android.app.spage: 0% user + 0.1% kernel / faults: 15 minor
  0.1% 6208/com.sohu.inputmethod.sogou.xiaomi: 0.1% user + 0% kernel / faults: 20 minor 1 major
  0.1% 7768/com.samsung.android.sidegesturepad: 0% user + 0% kernel / faults: 23 minor
  0.1% 31173/kworker/0:0-events: 0% user + 0.1% kernel
  0% 1/init: 0% user + 0% kernel
  0% 27/rcuop/2: 0% user + 0% kernel
  0% 33/rcuop/3: 0% user + 0% kernel
  0% 35/migration/4: 0% user + 0% kernel
  0% 40/rcuop/4: 0% user + 0% kernel
  0% 46/rcuop/5: 0% user + 0% kernel
  0% 52/rcuop/6: 0% user + 0% kernel
  0% 66/qrtr_ns: 0% user + 0% kernel
  0% 71/qmp_aop: 0% user + 0% kernel
  0% 354/com.google.android.documentsui: 0% user + 0% kernel / faults: 3 minor
  0% 932/zygote64: 0% user + 0% kernel / faults: 38 minor
  0% 1117/vendor.samsung.hardware.thermal@1.0-service: 0% user + 0% kernel
  0% 1129/qrtr_rx: 0% user + 0% kernel
  0% 1171/rmt_storage: 0% user + 0% kernel
  0% 1508/smdexe: 0% user + 0% kernel
  0% 1529/sechcserver: 0% user + 0% kernel
  0% 1709/qrtr_rx: 0% user + 0% kernel
  0% 2622/com.sec.imsservice: 0% user + 0% kernel / faults: 1 minor
  0% 3434/pageboostd: 0% user + 0% kernel / faults: 26 minor 1 major
  0% 3878/com.google.android.gms.persistent: 0% user + 0% kernel / faults: 73 minor 1 major
  0% 4295/com.google.android.gms: 0% user + 0% kernel / faults: 51 minor
  0% 4950/com.sec.android.diagmonagent: 0% user + 0% kernel / faults: 36 minor 1 major
  0% 5177/com.ext.star.wars: 0% user + 0% kernel / faults: 1 minor
  0% 5913/com.sec.android.app.myfiles: 0% user + 0% kernel
  0% 6121/kworker/1:1-events: 0% user + 0% kernel
  0% 15654/irq/22-9091000.: 0% user + 0% kernel
  0% 15655/irq/21-90b6400.: 0% user + 0% kernel
  0% 17048/com.samsung.c

**Comment by xiaoshanlin000** [comment]
去对应的调用地方判空, 有个空指针异常.
