### ISSUE TITLE
install instagram app in android version 11

### ISSUE THREAD

**Issue by 8306061644** [FBlackBox/BlackBox#117]
2022-04-21 11:24:40.321 3580-3595/? E/PowerUtils: getQuickChargerType
    java.io.FileNotFoundException: sys/class/power_supply/usb/quick_charge_type (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at java.io.FileReader.<init>(FileReader.java:72)
        at com.miui.powercenter.utils.n.b(Unknown Source:14)
        at com.miui.powercenter.batteryhistory.b.b(Unknown Source:24)
        at com.miui.powercenter.batteryhistory.b.a(Unknown Source:87)
        at com.miui.powercenter.batteryhistory.b.b(Unknown Source:45)
        at com.miui.powercenter.provider.PowerCenterProvider.call(Unknown Source:44)
        at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
        at android.os.Binder.execTransact(Binder.java:735)

**Comment by FBlackBox** [comment]
Irrelevant logs.
