### ISSUE TITLE
Running on oppo R11s device (Android 8.1), the 'invoke' method of ClassInvocationStub class is abnormal, resulting in the black screen of app cannot run.Below is the log, and the first two lines are the 'invoke' method I printed.

### ISSUE THREAD

**Issue by lz421421** [FBlackBox/BlackBox#12]
@Override
    public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
        MethodHook methodHook = mMethodHookMap.get(method.getName());
        if (methodHook == null) {
            try {
                System.out.println("-----ClassInvocationStub.java---invoke---->" + mBase + "-->" + method);
                return method.invoke(mBase, args);
            } catch (Throwable e) {
                System.out.println("-----ClassInvocationStub.java---invoke--Throwable-->" + mBase + "-->" + method);
                throw e.getCause();
            }
        }

        Object result = methodHook.beforeHook(mBase, method, args);
        if (result != null) {
            return result;
        }
        result = methodHook.hook(mBase, method, args);
        result = methodHook.afterHook(result);
        return result;
    }
--------------------------------------------------------------------------------------------------------------
I/System.out: -----ClassInvocationStub.java---invoke---->android.content.pm.IPackageManager$Stub$Proxy@7b31e74-->public abstract java.lang.String android.content.pm.IPackageManager.getInstallerPackageName(java.lang.String) throws android.os.RemoteException
I/System.out: -----ClassInvocationStub.java---invoke--Throwable-->android.content.pm.IPackageManager$Stub$Proxy@7b31e74-->public abstract java.lang.String android.content.pm.IPackageManager.getInstallerPackageName(java.lang.String) throws android.os.RemoteException
W/System.err: java.lang.IllegalArgumentException: Unknown package: com.hghcr.mmy
at android.os.Parcel.readException(Parcel.java:2033)
at android.os.Parcel.readException(Parcel.java:1975)
at android.content.pm.IPackageManager$Stub$Proxy.getInstallerPackageName(IPackageManager.java:4554)
at java.lang.reflect.Method.invoke(Native Method)
at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:111)
at java.lang.reflect.Proxy.invoke(Proxy.java:913)
at $Proxy36.getInstallerPackageName(Unknown Source)
at android.app.ApplicationPackageManager.getInstallerPackageName(ApplicationPackageManager.java:2120)
at org.chromium.base.BuildInfo.getAll(BuildInfo.java:11)
at org.chromium.content.browser.BrowserStartupController.nativeSetCommandLineFlags(Native Method)
at org.chromium.content.browser.BrowserStartupController.access$700(BrowserStartupController.java:18)
at org.chromium.content.browser.BrowserStartupController$4.run(BrowserStartupController.java:12)
at org.chromium.android_webview.AwBrowserProcess$$Lambda$0.run(Unknown Source:47)
at org.chromium.base.ThreadUtils.runOnUiThreadBlocking(ThreadUtils.java:10)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.startChromiumLocked(WebViewChromiumFactoryProvider.java:219)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.ensureChromiumStartedLocked(WebViewChromiumFactoryProvider.java:146)
at com.android.webview.chromium.WebViewChromiumFactoryProvider.startYourEngines(WebViewChromiumFactoryProvider.java:262)
at com.android.webview.chromium.WebViewChromium.init(WebViewChromium.java:30)
at android.webkit.WebView.<init>(WebView.java:663)
at android.webkit.WebView.<init>(WebView.java:593)
at android.webkit.WebView.<init>(WebView.java:576)
at android.webkit.WebView.<init>(WebView.java:563)
at android.webkit.WebView.<init>(WebView.java:553)
at com.joypac.commonsdk.base.utils.CommonDeviceUtil.getDefaultUserAgent_UI(CommonDeviceUtil.java:666)
at com.joypac.commonsdk.base.setting.net.SettingRequestController.requestSetting(SettingRequestController.java:82)
at com.joypac.commonsdk.base.setting.SettingController.requestSetting(SettingController.java:65)
at com.joypac.coresdk.core.MyApplicationManager.requesetSetting(MyApplicationManager.java:231)
at com.joypac.coresdk.core.MyApplicationManager.onCreate(MyApplicationManager.java:179)
at com.joypac.coresdk.core.CoreLifeCycleManger.onCreateApplication(CoreLifeCycleManger.java:179)
at com.joypac.coresdk.core.JoypacApplication.onCreate(JoypacApplication.java:60)
at com.google.utils.MyApplication.onCreate(MyApplication.java:14)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:222)
at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:139)
at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:366)
at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:285)
at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:89)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:197)
at android.app.ActivityThread.main(ActivityThread.java:7022)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:515)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:837)
V/ActivityThread: SCHEDULE 149 ENTER_ANIMATION_COMPLETE: 0 / android.os.BinderProxy@c046f80

**Comment by lz421421** [comment]
In 'IPackageManagerProxy','@ProxyMethod‘ is added to the solution cannot be found 'android.content.pm.IPackageManager.getInstallerPackageName'

@ProxyMethod(name = "getInstallerPackageName")
public static class GetInstallerPackageName extends MethodHook {
        @Override
        protected Object hook(Object who, Method method, Object[] args) throws Throwable {
            if (args != null && args.length > 0) {
                return args[0];
            }
            return BActivityThread.getAppPackageName();
        }
    }

**Comment by FBlackBox** [comment]
Thank you, I Fixed it. https://github.com/FBlackBox/BlackBox/commit/4c07c7d79531d854f6c49fa6d47dc5ab1a9df5d0
