### ISSUE TITLE
Error while opening the Facebook app

### ISSUE THREAD

**Issue by bascobasco** [FBlackBox/BlackBox#13]
1. Code used.

    The latest commit and api was used(From master this commit [Commit used ].      (https://github.com/FBlackBox/BlackBox/commit/286798c0c19bdaf4cb3310e4129b3259d47fa5bb))

2.  What caused the error.
        Opening the Facebook app.
        Link to the app :[Facebook app causing the error](https://play.google.com/store/apps/details?id=com.facebook.katana)

3.  What are the error logs:(note the app did not crash only the error got printed)

`com.facebook.katana E/RiskyStartupConfig: Failed to read risky config, some values left unset
    java.io.FileNotFoundException: /data/user/0/top.niunaijun.blackboxa64/blackbox/data/user/0/com.facebook.katana/files/risky_startup_config: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at X.0W5.A00(:48)
        at com.facebook.katana.app.FacebookApplication.A05(:266)
        at X.0V2.attachBaseContext(:41)
        at android.app.Application.attach(Application.java:361)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1160)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.newApplication(BaseInstrumentationDelegate.java:217)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.newApplication(AppInstrumentation.java:121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1316)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackreflection.utils.Reflector.callByCaller(Reflector.java:204)
        at top.niunaijun.blackreflection.BlackReflection$1.invoke(BlackReflection.java:142)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy97.makeApplication(Unknown Source)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:359)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:287)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8288)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8170)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
        at top.niunaijun.blackbox.fake.service.libcore.OsStub.invoke(OsStub.java:59)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy61.open(Unknown Source)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.FileInputStream.<init>(FileInputStream.java:160) 
        at X.0W5.A00(:48) 
        at com.facebook.katana.app.FacebookApplication.A05(:266) 
        at X.0V2.attachBaseContext(:41) 
        at android.app.Application.attach(Application.java:361) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1160) 
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.newApplication(BaseInstrumentationDelegate.java:217) 
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.newApplication(AppInstrumentation.java:121) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1316) `

**Comment by FBlackBox** [comment]
Just ignore it, maybe some of Facebook's logic
