### ISSUE TITLE
issue on oneplus android vesrion 11

### ISSUE THREAD

**Issue by SandeepRaval803** [FBlackBox/BlackBox#132]
2022-05-05 17:21:27.643 16167-16167/com.instagram.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.instagram.android, PID: 16167
    java.lang.RuntimeException: Unable to makeApplication
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:382)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:293)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8063)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:376)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:293) 
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168) 
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:8063) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 
2022-05-05 17:21:27.711 4554-4554/com.example.parallelspaceapp E/RippleView: addViewPhoto==0==lastNum==0==page==0==mGodHeadPhoto.size==0

**Comment by pubugre** [comment]
Ну и лох
