### ISSUE TITLE
Blackbox64运行某个应用时，出现下面错误

### ISSUE THREAD

**Issue by onexuan** [FBlackBox/BlackBox#142]
Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.jar", zip file "/data/app/com.box.art-xhsLkiaVggePS8NiWZ6Crw==/base.apk"],nativeLibraryDirectories=[/data/app/com.box.art-xhsLkiaVggePS8NiWZ6Crw==/lib/arm64, /data/app/com.box.art-xhsLkiaVggePS8NiWZ6Crw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:270)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:1005)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:1129)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1443)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackreflection.utils.Reflector.callByCaller(Reflector.java:204)
        at top.niunaijun.blackreflection.BlackReflection$1.invoke(BlackReflection.java:143)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy104.makeApplication(Unknown Source)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:368)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:293)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by FBlackBox** [comment]
这个错误无视即可

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2022年7月2日 星期六 下午 1:07，fonter.yang ***@***.***> 来信：

**Comment by onexuan** [comment]
@FBlackBox 加入盒里的应用运行不起来

**Comment by FSpaceCore** [comment]
欢迎测试SpaceCore：https://github.com/FSpaceCore/SpaceCore
