### ISSUE TITLE
[BUG] vivo android 12 无法创建桌面快捷方式

### ISSUE THREAD

**Issue by eastday** [FBlackBox/BlackBox#143]
vivo android 12 无法创建桌面快捷方式,试了其他的冰箱 ，伏羲 ，vmos，等都可以创建。
但是其他软件感觉没有这个软件这么稳定。

系统已经弹出授权提示框，并且已经授权。不是权限的问题。

**Comment by panzhi1** [comment]
快捷方式的有些方法没有Hook替换包名导致的，自己根据崩溃信息去hook对应方法

**Comment by mubasher380** [comment]
snapchat 应用程序崩溃这里是日志 
java.lang.SecurityException: Calling uid 10469 cannot set locusIdfor package com.snapchat.android
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3011)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:2995)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2920)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setActivityLocusContext(IActivityManager.java:8695)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy49.setActivityLocusContext(Unknown Source)
                                                                                                    	at android.app.Activity.setLocusContext(Activity.java:1101)
                                                                                                    	at com.snap.framework.contentcapture.ContentCaptureHelper.setLocusIdIfNew(Unknown Source:47)
                                                                                                    	at com.snap.framework.contentcapture.ContentCaptureHelper.onNonConversationPageAdded(SourceFile:25)
