### ISSUE TITLE
横屏游戏遇到的问题，Android 13上[BUG] 

### ISSUE THREAD

**Issue by frogontank** [FBlackBox/BlackBox#164]
在android 13上，装载了app到黑盒之后，启动相对app，如果app是横屏的，那么就报这个错，请问应该怎么解决呢？
java.lang.IllegalStateException: Method is not implemented
                                                                                                    	at android.os.IBinder.getExtension(IBinder.java:277)
                                                                                                    	at android.app.OplusActivityTaskManager$2.create(OplusActivityTaskManager.java:171)
                                                                                                    	at android.app.OplusActivityTaskManager$2.create(OplusActivityTaskManager.java:165)
                                                                                                    	at android.util.Singleton.get(Singleton.java:43)
                                                                                                    	at android.app.OplusActivityTaskManager.getService(OplusActivityTaskManager.java:158)
                                                                                                    	at android.app.OplusActivityTaskManager.isInSplitScreenMode(OplusActivityTaskManager.java:511)
                                                                                                    	at com.oplus.splitscreen.OplusSplitScreenManager.isInSplitScreenMode(OplusSplitScreenManager.java:312)
                                                                                                    	at android.app.OplusActivityThreadExtImpl.shouldInterceptConfigForSplit(OplusActivityThreadExtImpl.java:446)
                                                                                                    	at android.app.ActivityThread.performActivityConfigurationChanged(ActivityThread.java:6249)
                                                                                                    	at android.app.ActivityThread.performConfigurationChangedForActivity(ActivityThread.java:6190)
                                                                                                    	at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6550)
                                                                                                    	at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:53)
                                                                                                    	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2466)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:240)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8381)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by panzhi1** [comment]
是oppo手机吧。系统服务没有兼容Extension导致的。

**Comment by frogontank** [comment]
是oppo的手机。有什么解决方案吗？

**Comment by panzhi1** [comment]
尝试在BinderInvocationStub 中重写getExtension 调用mBaseBinder的getExtension方法

**Comment by frogontank** [comment]
> 尝试在BinderInvocationStub 中重写getExtension 调用mBaseBinder的getExtension方法

好。多谢提醒，祝万事如意。

**Comment by wzystal** [comment]
> > 尝试在BinderInvocationStub 中重写getExtension 调用mBaseBinder的getExtension方法
> 
> 好。多谢提醒，祝万事如意。

老哥，这个问题解决了吗？最近也遇到了

**Comment by 111304037** [comment]
> mBaseBinder

请问解决了吗，我在BinderInvocationStub加了getExtension MethodProxy还是不行
