### ISSUE TITLE
[BUG] 在android 上加载游戏时遇到闪退，提示找不到package

### ISSUE THREAD

**Issue by shengsheng0828** [FBlackBox/BlackBox#170]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gams.test/com.cocos.game.AppActivity}: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6680)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
                                                                                                    Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
                                                                                                    	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:471)
                                                                                                    	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:251)
                                                                                                    	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266)
                                                                                                    	at com.google.android.gms.ads.internal.util.zzs.zzc(Unknown Source:76)
                                                                                                    	at com.google.android.gms.internal.ads.zzbyj.zzs(Unknown Source:138)
                                                                                                    	at com.google.android.gms.internal.ads.zzcgd.zzC(Unknown Source:68)
                                                                                                    	at com.google.android.gms.internal.ads.zzcgd.zza(Unknown Source:12)
                                                                                                    	at com.google.android.gms.ads.internal.ClientApi.zzg(Unknown Source:7)
                                                                                                    	at com.google.android.gms.ads.internal.client.k.b(Unknown Source:9)
                                                                                                    	at com.google.android.gms.ads.internal.client.o.e(Unknown Source:5)
                                                                                                    	at com.google.android.gms.ads.internal.client.o.d(Unknown Source:79)
                                                                                                    	at com.google.android.gms.ads.internal.client.zzej.zzz(Unknown Source:14)
                                                                                                    	at com.google.android.gms.ads.internal.client.zzej.zzm(Unknown Source:48)
                                                                                                    	at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:5)
                                                                                                    	at com.cocos.game.Admob.init(Unknown Source:7)
                                                                                                    	at com.cocos.game.AppActivity.onCreate(Unknown Source:42)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7136)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7127)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
                                                                                                    	at com.baidu.bdcore.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(Unknown Source:2)
                                                                                                    	at com.baidu.bdcore.fake.delegate.AppInstrumentation.callActivityOnCreate(Unknown Source:3)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6680) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
                                                                                                    Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to find donor package: com.android.chrome
                                                                                                    	at android.webkit.WebViewFactory.fixupStubApplicationInfo(WebViewFactory.java:344)
                                                                                                    	at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:412)
                                                                                                    	at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:439)
                                                                                                    	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:251) 
                                                                                                    	at android.webkit.WebSettings.getDefaultUserAgent(WebSettings.java:1266) 
                                                                                                    	at com.google.android.gms.ads.internal.util.zzs.zzc(Unknown Source:76) 
                                                                                                    	at com.google.android.gms.internal.ads.zzbyj.zzs(Unknown Source:138) 
                                                                                                    	at com.google.android.gms.internal.ads.zzcgd.zzC(Unknown Source:68) 
                                                                                                    	at com.google.android.gms.internal.ads.zzcgd.zza(Unknown Source:12) 
                                                                                                    	at com.google.android.gms.ads.internal.ClientApi.zzg(Unknown Source:7) 
                                                                                                    	at com.google.android.gms.ads.internal.client.k.b(Unknown Source:9) 
                                                                                                    	at com.google.android.gms.ads.internal.client.o.e(Unknown Source:5) 
                                                                                                    	at com.google.android.gms.ads.internal.client.o.d(Unknown Source:79) 
                                                                                                    	at com.google.android.gms.ads.internal.client.zzej.zzz(Unknown Source:14) 
                                                                                                    	at com.google.android.gms.ads.internal.client.zzej.zzm(Unknown Source:48) 
                                                                                                    	at com.google.android.gms.ads.MobileAds.initialize(Unknown Source:5) 
                                                                                                    	at com.cocos.game.Admob.init(Unknown Source:7) 
                                                                                                    	at com.cocos.game.AppActivity.onCreate(Unknown Source:42) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7136) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7127) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
                                                                                                    	at com.baidu.bdcore.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(Unknown Source:2) 
                                                                                                    	at com.baidu.bdcore.fake.delegate.AppInstrumentation.callActivityOnCreate(Unknown Source:3) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:193) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6680) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by Kylin0828** [comment]
停止开发了。。。
