### ISSUE TITLE
鸿蒙3.0 打开小红书APP崩溃

### ISSUE THREAD

**Issue by Cleverlove7** [FBlackBox/BlackBox#171]

**Comment by Cleverlove7** [comment]
2023-07-19 17:27:31.892 17488-17488/com.xingin.xhs E/XY_Robust: download fail:   appVersionCode: 7950023
     appVersionName: 7.95.0
     patchVersion: 4
     patchMd5: 46eb9cd6faf9da4e2633a42882b9e6ac
     patchAbi: X64
     baseType: 8
     path: https://redgray.xhscdn.com/ui/Hotfix/prod/gray/Publish_Harmony/7.95.0/7950023/Patch/4/X64.zip
     forceDep: false
     patchStatus: downloading
     patchLocalPath: null
     invalidVersions: null
   java.lang.Throwable: md5 check failed
       at m44.e$b.onError(PatchManipulateImpl.kt:4)
       at zm1.a.N(DownloaderImpl.kt:3)
       at zm1.a.E(DownloaderImpl.kt:11)
       at zm1.a.k(Unknown Source:0)
       at zm1.a$d.a(DownloaderImpl.kt:4)
       at zm1.a$d.accept(Unknown Source:2)
       at dk4.l.b(LambdaObserver.java:2)
       at com.uber.autodispose.w.f(HalfSerializer.java:2)
       at com.uber.autodispose.q.b(AutoDisposingObserverImpl.java:2)
       at ik4.y0$a.e(ObservableObserveOn.java:8)
       at ik4.y0$a.run(ObservableObserveOn.java:3)
       at xj4.b$b.run(HandlerScheduler.java:1)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at ol4.c$a.run(SentryPlus.java:1)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8673)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

2023-07-19 17:27:31.497 17488-17488/com.xingin.xhs E/openSDK_LOG.SystemUtils: realGetPackageInfo exception
   android.content.pm.PackageManager$NameNotFoundException: com.tencent.mobileqq
       at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
       at com.tencent.open.utils.k.f(ProGuard:2)
       at com.tencent.open.utils.k.e(ProGuard:9)
       at com.tencent.open.utils.k.g(ProGuard:2)
       at com.tencent.open.utils.k.b(ProGuard:30)
       at com.tencent.open.b.b.a(ProGuard:10)
       at com.tencent.tauth.Tencent.<init>(ProGuard:3)
       at com.tencent.tauth.Tencent.createInstance(ProGuard:13)
       at oe3.c.m(QQAuthHelper.kt:2)
       at com.xingin.open_social.qq.spi.QQLoginSpiProxyImpl.init(Unknown Source:30)
       at r62.e.p(SocialManager.kt:2)
       at com.xingin.login.activity.WelcomeActivity.H9(WelcomeActivity.kt:1)
       at com.xingin.login.activity.WelcomeActivity.onCreate(WelcomeActivity.kt:5)
       at android.app.Activity.performCreate(Activity.java:8214)
       at android.app.Activity.performCreate(Activity.java:8202)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
       2023-07-19 17:27:31.580 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: realGetPackageInfo exception
   android.content.pm.PackageManager$NameNotFoundException: com.tencent.minihd.qq
       at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
       at com.tencent.open.utils.k.f(ProGuard:2)
       at com.tencent.open.utils.k.e(ProGuard:9)
       at com.tencent.open.utils.k.a(ProGuard:5)
       at com.tencent.tauth.Tencent.isSupportSSOLogin(ProGuard:3)
       at com.xingin.open_social.qq.spi.QQLoginSpiProxyImpl.isSupportQQLogin(Unknown Source:48)
       at j62.n0.e(SocialInstallHelper.kt:5)
       at j62.n0.b(Unknown Source:0)
       at j62.m0.apply(Unknown Source:4)
       at ik4.w0$a.b(ObservableMap.java:4)
       at ik4.p1$a.b(Unknown Source:2)
       at ik4.k1$a.run(ObservableScalarXMap.java:2)
       at ik4.u0.O1(ObservableJust.java:3)
       at uj4.t.d(Observable.java:4)
       at ik4.p1$b.run(Unknown Source:6)
       at lk4.l.b(ScheduledDirectTask.java:2)
       at lk4.l.call(Unknown Source:0)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at xz3.d.M(Unknown Source:21)
       at xz3.d.run(XYBaseTask.kt:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
2023-07-19 17:27:31.584 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: getAppVersionName return null. package= com.tencent.minihd.qq
2023-07-19 17:27:31.584 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: getTargetPackageInfo wrapper packageInfo is null
2023-07-19 17:27:31.585 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: getAppVersionName return null. package= com.tencent.mobileqq
2023-07-19 17:27:31.595 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: realGetPackageInfo exception
   android.content.pm.PackageManager$NameNotFoundException: com.tencent.tim
       at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
       at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
       at com.tencent.open.utils.k.f(ProGuard:2)
       at com.tencent.open.utils.k.e(ProGuard:9)
       at com.tencent.open.utils.k.a(ProGuard:5)
       at com.tencent.open.utils.k.d(ProGuard:1)
       at com.tencent.tauth.Tencent.isSupportSSOLogin(ProGuard:6)
       at com.xingin.open_social.qq.spi.QQLoginSpiProxyImpl.isSupportQQLogin(Unknown Source:48)
       at j62.n0.e(SocialInstallHelper.kt:5)
       at j62.n0.b(Unknown Source:0)
       at j62.m0.apply(Unknown Source:4)
       at ik4.w0$a.b(ObservableMap.java:4)
       at ik4.p1$a.b(Unknown Source:2)
       at ik4.k1$a.run(ObservableScalarXMap.java:2)
       at ik4.u0.O1(ObservableJust.java:3)
       at uj4.t.d(Observable.java:4)
       at ik4.p1$b.run(Unknown Source:6)
       at lk4.l.b(ScheduledDirectTask.java:2)
       at lk4.l.call(Unknown Source:0)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at xz3.d.M(Unknown Source:21)
       at xz3.d.run(XYBaseTask.kt:9)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929) top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240)
       at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4038)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4252)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at ol4.c$a.run(SentryPlus.java:1)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8673)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)

2023-07-19 17:27:33.964 17488-17488/com.xingin.xhs E/HMSSDK_PackageManagerHelper: Failed to get application signature certificate fingerprint.com.huawei.hwid
2023-07-19 17:27:33.964 17488-17488/com.xingin.xhs E/HMSSDK_PackageManagerHelper: Failed to get application signature certificate fingerprint.
2023-07-19 17:27:33.965 17488-17488/com.xingin.xhs E/HMSSDK_PackageManagerHelper: get PackageVersionCode failed android.content.pm.PackageManager$NameNotFoundException: com.huawei.hwid

**Comment by topcoco** [comment]
> 2023-07-19 17:27:31.892 17488-17488/com.xingin.xhs E/XY_Robust: download fail:   appVersionCode: 7950023
> 
>      appVersionName: 7.95.0
> 
>      patchVersion: 4
> 
>      patchMd5: 46eb9cd6faf9da4e2633a42882b9e6ac
> 
>      patchAbi: X64
> 
>      baseType: 8
> 
>      path: https://redgray.xhscdn.com/ui/Hotfix/prod/gray/Publish_Harmony/7.95.0/7950023/Patch/4/X64.zip
> 
>      forceDep: false
> 
>      patchStatus: downloading
> 
>      patchLocalPath: null
> 
>      invalidVersions: null
> 
>    java.lang.Throwable: md5 check failed
> 
>        at m44.e$b.onError(PatchManipulateImpl.kt:4)
> 
>        at zm1.a.N(DownloaderImpl.kt:3)
> 
>        at zm1.a.E(DownloaderImpl.kt:11)
> 
>        at zm1.a.k(Unknown Source:0)
> 
>        at zm1.a$d.a(DownloaderImpl.kt:4)
> 
>        at zm1.a$d.accept(Unknown Source:2)
> 
>        at dk4.l.b(LambdaObserver.java:2)
> 
>        at com.uber.autodispose.w.f(HalfSerializer.java:2)
> 
>        at com.uber.autodispose.q.b(AutoDisposingObserverImpl.java:2)
> 
>        at ik4.y0$a.e(ObservableObserveOn.java:8)
> 
>        at ik4.y0$a.run(ObservableObserveOn.java:3)
> 
>        at xj4.b$b.run(HandlerScheduler.java:1)
> 
>        at android.os.Handler.handleCallback(Handler.java:900)
> 
>        at android.os.Handler.dispatchMessage(Handler.java:103)
> 
>        at android.os.Looper.loop(Looper.java:219)
> 
>        at ol4.c$a.run(SentryPlus.java:1)
> 
>        at android.os.Handler.handleCallback(Handler.java:900)
> 
>        at android.os.Handler.dispatchMessage(Handler.java:103)
> 
>        at android.os.Looper.loop(Looper.java:219)
> 
>        at android.app.ActivityThread.main(ActivityThread.java:8673)
> 
>        at java.lang.reflect.Method.invoke(Native Method)
> 
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> 
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
> 
> 
> 
> 2023-07-19 17:27:31.497 17488-17488/com.xingin.xhs E/openSDK_LOG.SystemUtils: realGetPackageInfo exception
> 
>    android.content.pm.PackageManager$NameNotFoundException: com.tencent.mobileqq
> 
>        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
> 
>        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
> 
>        at com.tencent.open.utils.k.f(ProGuard:2)
> 
>        at com.tencent.open.utils.k.e(ProGuard:9)
> 
>        at com.tencent.open.utils.k.g(ProGuard:2)
> 
>        at com.tencent.open.utils.k.b(ProGuard:30)
> 
>        at com.tencent.open.b.b.a(ProGuard:10)
> 
>        at com.tencent.tauth.Tencent.<init>(ProGuard:3)
> 
>        at com.tencent.tauth.Tencent.createInstance(ProGuard:13)
> 
>        at oe3.c.m(QQAuthHelper.kt:2)
> 
>        at com.xingin.open_social.qq.spi.QQLoginSpiProxyImpl.init(Unknown Source:30)
> 
>        at r62.e.p(SocialManager.kt:2)
> 
>        at com.xingin.login.activity.WelcomeActivity.H9(WelcomeActivity.kt:1)
> 
>        at com.xingin.login.activity.WelcomeActivity.onCreate(WelcomeActivity.kt:5)
> 
>        at android.app.Activity.performCreate(Activity.java:8214)
> 
>        at android.app.Activity.performCreate(Activity.java:8202)
> 
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
> 
>        2023-07-19 17:27:31.580 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: realGetPackageInfo exception
> 
>    android.content.pm.PackageManager$NameNotFoundException: com.tencent.minihd.qq
> 
>        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
> 
>        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
> 
>        at com.tencent.open.utils.k.f(ProGuard:2)
> 
>        at com.tencent.open.utils.k.e(ProGuard:9)
> 
>        at com.tencent.open.utils.k.a(ProGuard:5)
> 
>        at com.tencent.tauth.Tencent.isSupportSSOLogin(ProGuard:3)
> 
>        at com.xingin.open_social.qq.spi.QQLoginSpiProxyImpl.isSupportQQLogin(Unknown Source:48)
> 
>        at j62.n0.e(SocialInstallHelper.kt:5)
> 
>        at j62.n0.b(Unknown Source:0)
> 
>        at j62.m0.apply(Unknown Source:4)
> 
>        at ik4.w0$a.b(ObservableMap.java:4)
> 
>        at ik4.p1$a.b(Unknown Source:2)
> 
>        at ik4.k1$a.run(ObservableScalarXMap.java:2)
> 
>        at ik4.u0.O1(ObservableJust.java:3)
> 
>        at uj4.t.d(Observable.java:4)
> 
>        at ik4.p1$b.run(Unknown Source:6)
> 
>        at lk4.l.b(ScheduledDirectTask.java:2)
> 
>        at lk4.l.call(Unknown Source:0)
> 
>        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 
>        at xz3.d.M(Unknown Source:21)
> 
>        at xz3.d.run(XYBaseTask.kt:9)
> 
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 
>        at java.lang.Thread.run(Thread.java:929)
> 
> 2023-07-19 17:27:31.584 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: getAppVersionName return null. package= com.tencent.minihd.qq
> 
> 2023-07-19 17:27:31.584 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: getTargetPackageInfo wrapper packageInfo is null
> 
> 2023-07-19 17:27:31.585 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: getAppVersionName return null. package= com.tencent.mobileqq
> 
> 2023-07-19 17:27:31.595 17488-17836/com.xingin.xhs E/openSDK_LOG.SystemUtils: realGetPackageInfo exception
> 
>    android.content.pm.PackageManager$NameNotFoundException: com.tencent.tim
> 
>        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:201)
> 
>        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:170)
> 
>        at com.tencent.open.utils.k.f(ProGuard:2)
> 
>        at com.tencent.open.utils.k.e(ProGuard:9)
> 
>        at com.tencent.open.utils.k.a(ProGuard:5)
> 
>        at com.tencent.open.utils.k.d(ProGuard:1)
> 
>        at com.tencent.tauth.Tencent.isSupportSSOLogin(ProGuard:6)
> 
>        at com.xingin.open_social.qq.spi.QQLoginSpiProxyImpl.isSupportQQLogin(Unknown Source:48)
> 
>        at j62.n0.e(SocialInstallHelper.kt:5)
> 
>        at j62.n0.b(Unknown Source:0)
> 
>        at j62.m0.apply(Unknown Source:4)
> 
>        at ik4.w0$a.b(ObservableMap.java:4)
> 
>        at ik4.p1$a.b(Unknown Source:2)
> 
>        at ik4.k1$a.run(ObservableScalarXMap.java:2)
> 
>        at ik4.u0.O1(ObservableJust.java:3)
> 
>        at uj4.t.d(Observable.java:4)
> 
>        at ik4.p1$b.run(Unknown Source:6)
> 
>        at lk4.l.b(ScheduledDirectTask.java:2)
> 
>        at lk4.l.call(Unknown Source:0)
> 
>        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 
>        at xz3.d.M(Unknown Source:21)
> 
>        at xz3.d.run(XYBaseTask.kt:9)
> 
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 
>        at java.lang.Thread.run(Thread.java:929) top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240)
> 
>        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134)
> 
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4038)
> 
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4252)
> 
>        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
> 
>        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
> 
>        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
> 
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
> 
>        at android.os.Handler.dispatchMessage(Handler.java:110)
> 
>        at android.os.Looper.loop(Looper.java:219)
> 
>        at ol4.c$a.run(SentryPlus.java:1)
> 
>        at android.os.Handler.handleCallback(Handler.java:900)
> 
>        at android.os.Handler.dispatchMessage(Handler.java:103)
> 
>        at android.os.Looper.loop(Looper.java:219)
> 
>        at android.app.ActivityThread.main(ActivityThread.java:8673)
> 
>        at java.lang.reflect.Method.invoke(Native Method)
> 
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> 
> 
> 
> 2023-07-19 17:27:33.964 17488-17488/com.xingin.xhs E/HMSSDK_PackageManagerHelper: Failed to get application signature certificate fingerprint.com.huawei.hwid
> 
> 2023-07-19 17:27:33.964 17488-17488/com.xingin.xhs E/HMSSDK_PackageManagerHelper: Failed to get application signature certificate fingerprint.
> 
> 2023-07-19 17:27:33.965 17488-17488/com.xingin.xhs E/HMSSDK_PackageManagerHelper: get PackageVersionCode failed android.content.pm.PackageManager$NameNotFoundException: com.huawei.hwid

加我QQ我帮你修复：3560000009玩也在写这样的框架

**Comment by RJMultiDev** [comment]
已经停更，可以考虑尝试huadows_fastapp作为替代品并提交issue。
