### ISSUE TITLE
[Other]广播发送 出现问题

### ISSUE THREAD

**Issue by jing1007209484** [FBlackBox/BlackBox#181]
]at java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader android.app.Application.getClassLoader()' on a null object reference java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.ClassLoader android.app.Application.getClassLoader()' on a null object reference
                                                                                                    	at top.niunaijun.blackbox.fake.service.IActivityManagerProxy$BroadcastIntent.hook(IActivityManagerProxy.java:419)
                                                                                                    	at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:120)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy79.broadcastIntent(Unknown Source)
                                                                                                    	at android.app.ContextImpl.sendBroadcast(ContextImpl.java:1009)
                                                                                                    	at android.content.ContextWrapper.sendBroadcast(ContextWrapper.java:444)
                                                                                                    	at com.Toolbox.AccessTools.BroadcastManager.lambda$sendBroadcastToService$0(BroadcastManager.java:36)
                                                                                                    	at com.Toolbox.AccessTools.BroadcastManager$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6840)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  top.niunaijun.blackbox.fake.service.IActivityManagerProxy$BroadcastIntent . hook (IActivityManagerProxy.java : 419 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  top.niunaijun.blackbox.fake.hook.ClassInvocationStub . invoke (ClassInvocationStub.java : 120 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  java.lang.reflect.Proxy . invoke (Proxy.java : 1006 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  $Proxy79 . broadcastIntent (null : -1 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  android.app.ContextImpl . sendBroadcast (ContextImpl.java : 1009 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  android.content.ContextWrapper . sendBroadcast (ContextWrapper.java : 444 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  com.Toolbox.AccessTools.BroadcastManager . lambda$sendBroadcastToService$0 (BroadcastManager.java : 36 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  com.Toolbox.AccessTools.BroadcastManager$$ExternalSyntheticLambda0 . run (null : 4 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  android.os.Handler . handleCallback (Handler.java : 873 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  android.os.Handler . dispatchMessage (Handler.java : 99 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  android.os.Looper . loop (Looper.java : 193 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  android.app.ActivityThread . main (ActivityThread.java : 6840 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  java.lang.reflect.Method . invoke (Method.java : -2 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  com.android.internal.os.RuntimeInit$MethodAndArgsCaller . run (RuntimeInit.java : 493 )
2024-08-13 19:51:13.501  6621-6621  app-- com....ionHandler top.niunaijun.blackboxa32            E  [main]at  com.android.internal.os.ZygoteInit . main (ZygoteInit.java : 860 )

**Comment by RJMultiDev** [comment]
已经停更，可以考虑尝试huadows_fastapp作为替代品并提交issue。
