### ISSUE TITLE
instagram launch error

### ISSUE THREAD

**Issue by mostafa1368** [FBlackBox/BlackBox#22]
![photo_2022-03-05_14-18-05](https://user-images.githubusercontent.com/13781476/156880111-8e5e8018-18cf-4a4a-bb44-47d80044e468.jpg)

`2022-03-05 14:29:38.169 26701-26701/com.instagram.android E/MessageQueue: IdleHandler threw exception
    java.lang.SecurityException: Permission Denial: getIntentSender() from pid=26701, uid=11028, (need uid=10161) is not allowed to send as package com.instagram.android
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithSourceToken(IActivityManager.java:6628)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy35.getIntentSenderWithSourceToken(Unknown Source)
        at java.lang.reflect.Method.invoke(Native Method)
        at X.0RW.A00(:8)
        at X.0RW.invoke(:121)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy107.getIntentSenderWithSourceToken(Unknown Source)
        at android.app.PendingIntent.getActivity(PendingIntent.java:356)
        at android.app.PendingIntent.getActivity(PendingIntent.java:314)
        at X.0LP.A02(:8)
        at X.0kL.A01(:13)
        at X.0kH.A02(:24)
        at X.2VN.Atb(:319)
        at X.0dK.onQueueIdle(:30)
        at X.0yR.queueIdle(:19)
        at android.os.MessageQueue.next(MessageQueue.java:405)
        at android.os.Looper.loop(Looper.java:197)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
2022-03-05 14:29:38.232 26701-26701/com.instagram.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.instagram.android, PID: 26701
    java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x4200010 (has extras) } in com.instagram.push.FbnsInitBroadcastReceiver@a632b0f
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1656)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: java.lang.SecurityException: Permission Denial: getIntentSender() from pid=26701, uid=11028, (need uid=10161) is not allowed to send as package com.instagram.android
        at android.os.Parcel.createException(Parcel.java:2088)
        at android.os.Parcel.readException(Parcel.java:2056)
        at android.os.Parcel.readException(Parcel.java:2004)
        at android.app.IActivityManager$Stub$Proxy.getIntentSenderWithSourceToken(IActivityManager.java:6628)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy35.getIntentSenderWithSourceToken(Unknown Source)
        at java.lang.reflect.Method.invoke(Native Method)
        at X.0RW.A00(:8)
        at X.0RW.invoke(:121)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy107.getIntentSenderWithSourceToken(Unknown Source)
        at android.app.PendingIntent.getActivity(PendingIntent.java:356)
        at android.app.PendingIntent.getActivity(PendingIntent.java:314)
        at X.0LP.A02(:8)
        at X.0kL.A01(:13)
        at X.0kH.A02(:24)
        at X.2VN.Atb(:319)
        at com.instagram.push.FbnsInitBroadcastReceiver.onReceive(:268)
        at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1646)
        at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:7948) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075) 
2022-03-05 14:29:38.385 26701-26701/com.instagram.android E/CatchMeIfYouCan: Not killing process because SILENT_EXIT flag is not set.
`

instagram shortcut error 
After watching the splash and about 20 seconds, the program closes

**Comment by FBlackBox** [comment]
What Android version?

**Comment by mostafa1368** [comment]
Android 10
Samsung A20s

**Comment by FBlackBox** [comment]
Maybe the frameworks have been changed by the manufacturer. I can't find the relevant code in the source code. Please try: https://github.com/FBlackBox/BlackBox/commit/ba49cc26c865a9a5629dc33380ffbd949074b338

**Comment by mostafa1368** [comment]
I updated the build version of the project and Gradle Wallper, I set the sdk app to 32

**Comment by FBlackBox** [comment]
Please use the new code to see if it is repaired? feedback for me
