### ISSUE TITLE
Run the latest code ,Toast ‘安装成功’,But the installation failed.Huawei STA-AL00 (Android 9) and OPPO R11s (Android 8.1.0),Here is the log

### ISSUE THREAD

**Issue by lz421421** [FBlackBox/BlackBox#27]
`W/System.err: java.lang.NullPointerException: Attempt to read from field 'int top.niunaijun.blackbox.core.system.pm.BPackageSettings.appId' on a null object reference
at top.niunaijun.blackbox.core.system.pm.PackageManagerCompat.generateApplicationInfo(PackageManagerCompat.java:292)
at top.niunaijun.blackbox.core.system.pm.Settings.updatePackageLP(Settings.java:189)
at top.niunaijun.blackbox.core.system.pm.Settings.scanPackage(Settings.java:164)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUserLocked(BPackageManagerService.java:717)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUser(BPackageManagerService.java:523)
at top.niunaijun.blackbox.core.system.pm.IBPackageManagerService$Stub.onTransact(IBPackageManagerService.java:504)
at android.os.Binder.execTransact(Binder.java:739)`
`W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.res.Resources.getXml(int)' on a null object reference
at top.niunaijun.blackbox.core.system.accounts.RegisteredServicesParser.getParser(RegisteredServicesParser.java:23)
at top.niunaijun.blackbox.core.system.accounts.BAccountManagerService.generateServicesMap(BAccountManagerService.java:1422)
at top.niunaijun.blackbox.core.system.accounts.BAccountManagerService.loadAuthenticatorCache(BAccountManagerService.java:1414)
at top.niunaijun.blackbox.core.system.accounts.BAccountManagerService.onPackageUninstalled(BAccountManagerService.java:116)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.onPackageUninstalled(BPackageManagerService.java:787)
at top.niunaijun.blackbox.core.system.pm.Settings.updatePackageLP(Settings.java:201)
at top.niunaijun.blackbox.core.system.pm.Settings.scanPackage(Settings.java:164)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUserLocked(BPackageManagerService.java:717)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUser(BPackageManagerService.java:523)
at top.niunaijun.blackbox.core.system.pm.IBPackageManagerService$Stub.onTransact(IBPackageManagerService.java:504)
at android.os.Binder.execTransact(Binder.java:739)`
![59S%~)`YEZ3O Q%B0LBZESL](https://user-images.githubusercontent.com/7537213/157028805-f307d8ae-55c1-487e-8536-e35d02a9a275.png)

**Comment by lz421421** [comment]
`W/System.err: java.lang.NullPointerException: Attempt to read from field 'int top.niunaijun.blackbox.core.system.pm.BPackageSettings.appId' on a null object reference
at top.niunaijun.blackbox.core.system.pm.PackageManagerCompat.generateApplicationInfo(PackageManagerCompat.java:292)
at top.niunaijun.blackbox.core.system.pm.Settings.updatePackageLP(Settings.java:189)
at top.niunaijun.blackbox.core.system.pm.Settings.scanPackage(Settings.java:164)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUserLocked(BPackageManagerService.java:717)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUser(BPackageManagerService.java:523)
at top.niunaijun.blackbox.core.system.pm.IBPackageManagerService$Stub.onTransact(IBPackageManagerService.java:504)
at android.os.Binder.execTransact(Binder.java:739)

W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.res.Resources.getXml(int)' on a null object reference
at top.niunaijun.blackbox.core.system.accounts.RegisteredServicesParser.getParser(RegisteredServicesParser.java:23)
at top.niunaijun.blackbox.core.system.accounts.BAccountManagerService.generateServicesMap(BAccountManagerService.java:1422)
at top.niunaijun.blackbox.core.system.accounts.BAccountManagerService.loadAuthenticatorCache(BAccountManagerService.java:1414)
at top.niunaijun.blackbox.core.system.accounts.BAccountManagerService.onPackageUninstalled(BAccountManagerService.java:116)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.onPackageUninstalled(BPackageManagerService.java:787)
at top.niunaijun.blackbox.core.system.pm.Settings.updatePackageLP(Settings.java:201)
at top.niunaijun.blackbox.core.system.pm.Settings.scanPackage(Settings.java:164)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUserLocked(BPackageManagerService.java:717)
at top.niunaijun.blackbox.core.system.pm.BPackageManagerService.installPackageAsUser(BPackageManagerService.java:523)
at top.niunaijun.blackbox.core.system.pm.IBPackageManagerService$Stub.onTransact(IBPackageManagerService.java:504)
at android.os.Binder.execTransact(Binder.java:739)`

**Comment by lz421421** [comment]
![Uploading UL~3JI1{_]CQ4VEDI25EFYY.png…]()

**Comment by lz421421** [comment]
![UL~3JI1{_ CQ4VEDI25EFYY](https://user-images.githubusercontent.com/7537213/157030174-9c52a623-d752-4a79-a2af-e47b2ec9b342.png)

**Comment by FBlackBox** [comment]
Are you using the latest code?
