### ISSUE TITLE
高德地图运行崩溃，百度地图正常

### ISSUE THREAD

**Issue by crazyn2** [FBlackBox/BlackBox#30]
Android 10 , MatePad Pro, emui11
```
2022-03-09 00:41:21.528 1175-1175/com.autonavi.minimap E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.jar", zip file "/data/app/com.autonavi.minimap-xNTZuxCY3FPujK17RUFRjg==/base.apk"],nativeLibraryDirectories=[/data/app/com.autonavi.minimap-xNTZuxCY3FPujK17RUFRjg==/lib/arm64, /data/app/com.autonavi.minimap-xNTZuxCY3FPujK17RUFRjg==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:270)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:989)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:1113)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1405)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackreflection.utils.Reflector.callByCaller(Reflector.java:204)
        at top.niunaijun.blackreflection.BlackReflection$1.invoke(BlackReflection.java:142)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy102.makeApplication(Unknown Source)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:364)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:292)
        at top.niunaijun.blackbox.app.BActivityThread.createService(BActivityThread.java:206)
        at top.niunaijun.blackbox.app.dispatcher.AppServiceDispatcher.getOrCreateService(AppServiceDispatcher.java:232)
        at top.niunaijun.blackbox.app.dispatcher.AppServiceDispatcher.onBind(AppServiceDispatcher.java:53)
        at top.niunaijun.blackbox.proxy.ProxyService.onBind(ProxyService.java:35)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:4670)
        at android.app.ActivityThread.access$2900(ActivityThread.java:251)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2324)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Comment by FBlackBox** [comment]
这个日志没关系的，是native的崩溃，暂时不好处理。

**Comment by lpcdma** [comment]
> 这个日志没关系的，是native的崩溃，暂时不好处理。

是native路径重定位问题么，不行就加个吧

**Comment by FBlackBox** [comment]
> > 这个日志没关系的，是native的崩溃，暂时不好处理。
> 
> 是native路径重定位问题么，不行就加个吧

暂不清楚，等先开发完其他模块先。
