### ISSUE TITLE
切换到UserId 1, 打开百度地图崩溃

### ISSUE THREAD

**Issue by crazyn2** [FBlackBox/BlackBox#36]
小米Redmi k40, Android 11
错误日志
```
2022-03-11 10:24:42.965 15567-15567/com.baidu.BaiduMap E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.baidu.nps.hook.component.NPSComponentFactory" on path: DexPathList[[zip file "/data/app/~~OXQD7h7cGo7-bpo72u6A7w==/com.baidu.BaiduMap-vfvKqPoMhllErwrmMfjYOw==/base.apk"],nativeLibraryDirectories=[/data/app/~~OXQD7h7cGo7-bpo72u6A7w==/com.baidu.BaiduMap-vfvKqPoMhllErwrmMfjYOw==/lib/arm64, /data/app/~~OXQD7h7cGo7-bpo72u6A7w==/com.baidu.BaiduMap-vfvKqPoMhllErwrmMfjYOw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:262)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:907)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:960)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1216)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackreflection.utils.Reflector.callByCaller(Reflector.java:204)
        at top.niunaijun.blackreflection.BlackReflection$1.invoke(BlackReflection.java:142)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy106.makeApplication(Unknown Source)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:358)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:286)
        at top.niunaijun.blackbox.app.BActivityThread.createService(BActivityThread.java:200)
        at top.niunaijun.blackbox.app.dispatcher.AppServiceDispatcher.getOrCreateService(AppServiceDispatcher.java:232)
        at top.niunaijun.blackbox.app.dispatcher.AppServiceDispatcher.onBind(AppServiceDispatcher.java:53)
        at top.niunaijun.blackbox.proxy.ProxyService.onBind(ProxyService.java:35)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:4322)
        at android.app.ActivityThread.access$1800(ActivityThread.java:257)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by FBlackBox** [comment]
确实，待修复。
