### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by ArcyMods** [FBlackBox/BlackBox#42]
Hello, so i was testing an application named **com.pixel.gun3d**. but ran into an issue:

```
2022-03-16 21:05:32.786 7684-7684/com.pixel.gun3d E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pixel.gun3d, PID: 7684
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pixel.gun3d/com.AutoSkillz.ASLoginActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
        at android.os.Parcel.readException(Parcel.java:1962)
        at android.os.Parcel.readException(Parcel.java:1900)
        at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5704)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.invoke(ClassInvocationStub.java:110)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy32.setRequestedOrientation(Unknown Source)
        at android.app.Activity.setRequestedOrientation(Activity.java:6132)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.checkActivity(AppInstrumentation.java:114)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:132)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7529) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
```

Here's the link to the apk: https://www.mediafire.com/file/ewkqybe64nfwg96/AutoSkillz_PG3D_Mod.apk/file

**Comment by FBlackBox** [comment]
This is a bug that appeared in Android 8.0
