### ISSUE TITLE
samsung SM-N9500 android 9 闪退

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#43]
https://pastebin.com/KpgszuQW

03/17 18:52:13: Launching 'app' on samsung SM-N9500.
Install successfully finished in 6 s 77 ms.
$ adb shell am start -n "top.niunaijun.blackboxa32/zzz.adplatform.framework.ZZZ_SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 3469 on device 'samsung-sm_n9500-ce0817181c15e0290d7e'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/Zeus/init: ZeusManager init, context = top.niunaijun.blackboxa.app.App@516cc2c, hParam = com.bytedance.pangle.GlobalParam@2f286f5
E/FlippedV1Impl: V1 invokeHiddenApiRestrictions success.
W/Zeus/init: ZeusManager disableApiWarningShownForAndroidP, true
W/Zeus/provider: Need to init system provider info start [packageNam:=top.niunaijun.blackboxa32],[processName=top.niunaijun.blackboxa32],[authority:top.niunaijun.blackboxa32.pangle.provider.proxy.main]
W/Zeus/provider: Init system provider info finish [packageNam:=top.niunaijun.blackboxa32],[processName=top.niunaijun.blackboxa32],[authority:top.niunaijun.blackboxa32.pangle.provider.proxy.main]
Connected to process 4186 on device 'samsung-sm_n9500-ce0817181c15e0290d7e'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ackboxa32:blac: The ClassLoaderContext is a special shared library.
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.HCallbackProxy@7d448af
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IAccountManagerProxy@ade9ea7
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IWifiManagerProxy@f2ebb9f
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IPackageManagerProxy@1faa331
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IDeviceIdentifiersPolicyProxy@fa075f0
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.INetworkManagementServiceProxy@78662fa
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IAppWidgetManagerProxy@c5057b4
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IDevicePolicyManagerProxy@4c2969e
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IPhoneSubInfoProxy@e5b4e38
W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
W/System.err:     at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.injectHook(ClassInvocationStub.java:52)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.injectAll(HookManager.java:172)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.init(HookManager.java:153)
W/System.err:     at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:158)
W/System.err:     at top.niunaijun.blackboxa.view.main.BlackBoxLoader.attachBaseContext(BlackBoxLoader.kt:87)
W/System.err:     at top.niunaijun.blackboxa.app.AppManager.doAttachBaseContext(AppManager.kt:25)
W/System.err:     at top.niunaijun.blackboxa.app.App.attachBaseContext(App.kt:30)
W/System.err:     at android.app.Application.attach(Application.java:237)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193)
W/System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:237)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.libcore.OsStub@3ccdb76
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.ILocationManagerProxy@a33902
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IPowerManagerProxy@cf93d7c
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IActivityManagerProxy@d551d81
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IStorageManagerProxy@1c4fdac
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IVibratorServiceProxy@bf4cd6
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IContextHubServiceProxy@93592b0
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.INotificationManagerProxy@b5499ba
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IWindowManagerProxy@5a29786
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.context.RestrictionsManagerStub@1bf115e
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IUserManagerProxy@aa5f2f8
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.ILauncherAppsProxy@83ab7c2
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IJobServiceProxy@866c63c
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.ITelephonyManagerProxy@b0450e6
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IPermissionManagerProxy@877f640
W/System.err: java.lang.ClassNotFoundException: android.permission.IPermissionManager$Stub
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:453)
W/System.err:     at java.lang.Class.forName(Class.java:378)
W/System.err:     at top.niunaijun.blackreflection.BlackReflection.getClassNameByBlackClass(BlackReflection.java:246)
W/System.err:     at top.niunaijun.blackreflection.BlackReflection.create(BlackReflection.java:53)
W/System.err:     at black.android.permission.BRIPermissionManagerStub.get(BRIPermissionManagerStub.java:13)
W/System.err:     at top.niunaijun.blackbox.fake.service.IPermissionManagerProxy.getWho(IPermissionManagerProxy.java:30)
W/System.err:     at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.injectHook(ClassInvocationStub.java:51)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.injectAll(HookManager.java:172)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.init(HookManager.java:153)
W/System.err:     at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:158)
W/System.err:     at top.niunaijun.blackboxa.view.main.BlackBoxLoader.attachBaseContext(BlackBoxLoader.kt:87)
W/System.err:     at top.niunaijun.blackboxa.app.AppManager.doAttachBaseContext(AppManager.kt:25)
W/System.err:     at top.niunaijun.blackboxa.app.App.attachBaseContext(App.kt:30)
W/System.err:     at android.app.Application.attach(Application.java:237)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193)
W/System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:237)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.permission.IPermissionManager$Stub" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/top.niunaijun.blackboxa32-4bBdgmsamp1WurdgDYSy3Q==/base.apk"],nativeLibraryDirectories=[/data/app/top.niunaijun.blackboxa32-4bBdgmsamp1WurdgDYSy3Q==/lib/arm, /data/app/top.niunaijun.blackboxa32-4bBdgmsamp1WurdgDYSy3Q==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W/System.err: 	... 26 more
W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.IInterface black.android.permission.IPermissionManagerStubStatic.asInterface(android.os.IBinder)' on a null object reference
W/System.err:     at top.niunaijun.blackbox.fake.service.IPermissionManagerProxy.getWho(IPermissionManagerProxy.java:30)
W/System.err:     at top.niunaijun.blackbox.fake.hook.ClassInvocationStub.injectHook(ClassInvocationStub.java:51)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.injectAll(HookManager.java:172)
W/System.err:     at top.niunaijun.blackbox.fake.hook.HookManager.init(HookManager.java:153)
W/System.err:     at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:158)
W/System.err:     at top.niunaijun.blackboxa.view.main.BlackBoxLoader.attachBaseContext(BlackBoxLoader.kt:87)
W/System.err:     at top.niunaijun.blackboxa.app.AppManager.doAttachBaseContext(AppManager.kt:25)
W/System.err:     at top.niunaijun.blackboxa.app.App.attachBaseContext(App.kt:30)
W/System.err:     at android.app.Application.attach(Application.java:237)
W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193)
W/System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:237)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:214)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.context.ContentServiceStub@dc24435
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IMediaSessionManagerProxy@5cd7717
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IMediaRouterServiceProxy@734c2e9
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IAppOpsManagerProxy@de9e02b
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IGraphicsStatsProxy@75b94a0
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.ITelephonyRegistryProxy@3350c2a
D/HookManager: injectHook: top.niunaijun.blackbox.fake.delegate.AppInstrumentation@9f23764
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IAutofillManagerProxy@45a3dcd
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IAccessibilityManagerProxy@c11e3ef
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IPersistentDataBlockServiceProxy@74c61e7
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IShortcutManagerProxy@833d739
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IAlarmManagerProxy@aabd1fb
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IConnectivityManagerProxy@c4ea6ad
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IStorageStatsManagerProxy@8f005cf
D/HookManager: injectHook: top.niunaijun.blackbox.fake.service.IDisplayManagerProxy@721be1
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
I/chatty: uid=10402 top.niunaijun.blackboxa32:black identical 1 line
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
I/chatty: uid=10402 top.niunaijun.blackboxa32:black identical 1 line
W/PackageParser: No actions in intent filter at /data/app/com.huawei.hwid-DjQL57H2K8n7dVC48uOZFA==/base.apk Binary XML file line #0
D/BPackageInstallerService: installPackageAsUser: CreateUserExecutor exec: 0
D/BPackageInstallerService: installPackageAsUser: CreatePackageExecutor exec: 0
D/BPackageInstallerService: installPackageAsUser: CopyExecutor exec: 0
D/Settings: loaded Package: com.huawei.hwid
D/BroadcastManager: register: com.huawei.hwid, size: 12
D/BPackageManagerService: onPackageInstalled: com.huawei.hwid, userId: -1
D/BPackageManagerService: install finish: 2747ms
D/BPackageInstallerService: installPackageAsUser: CreateUserExecutor exec: 0
D/BPackageInstallerService: installPackageAsUser: CreatePackageExecutor exec: 0
D/VirtualM: Try to copy plugin's cup arch: armeabi-v7a
D/VirtualM: Found plugin's cup arch dir: armeabi-v7a
D/VirtualM: verify so libImSDK.so
D/VirtualM: copy so lib/armeabi-v7a/libImSDK.so of armeabi-v7a
D/VirtualM: verify so libNat.so
D/VirtualM: copy so lib/armeabi-v7a/libNat.so of armeabi-v7a
D/VirtualM: verify so libconceal.so
D/VirtualM: copy so lib/armeabi-v7a/libconceal.so of armeabi-v7a
D/VirtualM: verify so libweibosdkcore.so
D/VirtualM: copy so lib/armeabi-v7a/libweibosdkcore.so of armeabi-v7a
D/VirtualM: verify so libwind.so
D/VirtualM: copy so lib/armeabi-v7a/libwind.so of armeabi-v7a
D/VirtualM: verify so libxcrash.so
D/VirtualM: copy so lib/armeabi-v7a/libxcrash.so of armeabi-v7a
D/VirtualM: verify so libxcrash_dumper.so
D/VirtualM: copy so lib/armeabi-v7a/libxcrash_dumper.so of armeabi-v7a
D/VirtualM: Done! +246ms
D/BPackageInstallerService: installPackageAsUser: CopyExecutor exec: 0
D/Settings: loaded Package: net.pandapaint.draw
D/BroadcastManager: register: net.pandapaint.draw, size: 6
D/BPackageManagerService: onPackageInstalled: net.pandapaint.draw, userId: 0
D/BPackageManagerService: install finish: 1868ms

**Comment by FBlackBox** [comment]
你这个已经是很久之前的版本了，建议更新BCore，更新之后如果再有问题再来提issue
