### ISSUE TITLE
android 6 OPPO

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#56]
SIG: 9, fg: true, exiting: false, main process: true, time: 20220321142329
    State in disk: 'f'
        at android.os.Process.sendSignal(Native Method)
        at android.os.Process.killProcess(Process.java:1070)
        at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:100)
        at top.niunaijun.blackbox.core.CrashHandler.uncaughtException(CrashHandler.java:30)
        at com.umeng.analytics.pro.o.uncaughtException(SourceFile:3)
        at com.uc.crashsdk.e.a(SourceFile:574)
        at com.uc.crashsdk.e.uncaughtException(SourceFile:1)
        at com.kwad.sdk.crash.b.d.uncaughtException(SourceFile)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

**Comment by FBlackBox** [comment]
Please provide APK
