### ISSUE TITLE
android 7 samsung

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#57]
--------- beginning of crash
2022-03-21 14:38:18.895 4603-4603/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ygmh.comic, PID: 4603
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
     Caused by: java.lang.Exception: Oops!
        at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:201)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.execStartActivity(BaseInstrumentationDelegate.java:348)
        at android.app.Activity.startActivityForResult(Activity.java:4238)
        at ᨤ.ὶ.ᮻ.ᵵ.startActivityForResult(SourceFile:6)
        at android.app.Activity.startActivityForResult(Activity.java:4196)
        at ᨤ.ὶ.ᮻ.ᵵ.startActivityForResult(SourceFile:3)
        at android.app.Activity.startActivity(Activity.java:4535)
        at android.app.Activity.startActivity(Activity.java:4503)
        at ᵵ.ᶫ.ᮻ.ᜰ.ᮻ.ᨤ(SourceFile:6)
        at com.ygmh.comic.mvvm.view.activity.launcheractivity.LauncherRotationActivity.₮(SourceFile:1)
        at com.ygmh.comic.mvvm.view.activity.launcheractivity.LauncherRotationActivity.ᮻ(SourceFile:1)
        at ᵵ.ᦟ.ᮻ.ᵵ.ᚉ.ᮻ.ằ.ᮻ.onError(SourceFile:3)
        at com.kwad.sdk.core.request.d$11$1.run(SourceFile)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6176)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781) 
     Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ygmh.comic/com.ygmh.comic.mvvm.view.activity.splashactivity.SplashRotationActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1805)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
        at java.lang.reflect.Method.invoke(Native Method)
        at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:199)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.execStartActivity(BaseInstrumentationDelegate.java:348) 
        at android.app.Activity.startActivityForResult(Activity.java:4238) 
        at ᨤ.ὶ.ᮻ.ᵵ.startActivityForResult(SourceFile:6) 
        at android.app.Activity.startActivityForResult(Activity.java:4196) 
        at ᨤ.ὶ.ᮻ.ᵵ.startActivityForResult(SourceFile:3) 
        at android.app.Activity.startActivity(Activity.java:4535) 
        at android.app.Activity.startActivity(Activity.java:4503) 
        at ᵵ.ᶫ.ᮻ.ᜰ.ᮻ.ᨤ(SourceFile:6) 
        at com.ygmh.comic.mvvm.view.activity.launcheractivity.LauncherRotationActivity.₮(SourceFile:1) 
        at com.ygmh.comic.mvvm.view.activity.launcheractivity.LauncherRotationActivity.ᮻ(SourceFile:1) 
        at ᵵ.ᦟ.ᮻ.ᵵ.ᚉ.ᮻ.ằ.ᮻ.onError(SourceFile:3) 
        at com.kwad.sdk.core.request.d$11$1.run(SourceFile) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6176) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by FBlackBox** [comment]
Fix https://github.com/FBlackBox/BlackBox/commit/7fe624d0f6792231f7b3d2446e145493799c9958
