### ISSUE TITLE
Fatal Exception: android.content.pm.PackageManager$NameNotFoundException (Redmi 10 android version 10)

### ISSUE THREAD

**Issue by bascobasco** [FBlackBox/BlackBox#6]
Fatal Exception: android.content.pm.PackageManager$NameNotFoundException: b4a.intjambklub
       at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:427)
       at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:408)
       at anywheresoftware.b4a.keywords.B4AApplication.getLabelName(B4AApplication.java:20)
       at b4a.intjambklub.main._activity_pause(main.java:1245)
       at java.lang.reflect.Method.invoke(Method.java)
       at anywheresoftware.b4a.BA.raiseEvent2(BA.java:213)
       at b4a.intjambklub.main.onPause(main.java:284)
       at android.app.Activity.performPause(Activity.java:8096)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1507)
       at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnPause(BaseInstrumentationDelegate.java:312)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4600)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4561)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4510)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7561)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by crazyn2** [comment]
Please provide the phone type and android version and do the same thing at another issue opened by you.

**Comment by FBlackBox** [comment]
After testing, there is no problem. Please try to compile and run with the latest code
