### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by liuyueban9** [FBlackBox/BlackBox#67]
**Describe the bug** / **app闪退**
app安装后打开闪退

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
vivo / Android11

**Logcat** / **日志**
2022-03-28 16:43:03.891 32132-32294/? D/MemoryCeilingMonitor: [handleMemoryCalculate]
2022-03-28 16:43:03.891 32132-32294/? D/MemoryCeilingMonitor: [calculate] tot: 7396208, max: 268435456, free: 1783928, heap: 5612280, per: 0.02090737223625183
2022-03-28 16:43:06.095 32132-461/? D/MSF.C.NetConnTag.true: netRecv ssoSeq:-485859223 uin:*7940 cmd:BS08PTQ9FS85K34EOAgwKSIEIjsvKAgpLQ -485858295 cross:0 socketEngineID: 0 socket: 186019684
2022-03-28 16:43:06.096 32132-390/? I/MSF.S.AppProcessManager: SendToApp PUSH process:com.tencent.mobileqq fromServiceMsg: FromServiceMsg msName:onRecvPushMsg ssoSeq:-485859223 serviceCmd:OnlinePush.PbPushGroupMsg appSeq:-485859223 failCode:1000 cost = 0 needBoot=true from.len = 830
2022-03-28 16:43:06.098 32157-32177/? D/MSF.D.Proxy: onRecvServicePushResp, fromServiceMsg cmd = OnlinePush.PbPushGroupMsg, ssoSeq = -485859223, length = 830
2022-03-28 16:43:06.101 32157-571/? I/troop_ext: onTroopReceiveOrSendMsg troopInfo is null or not eliminated. troopUin: 6465306
2022-03-28 16:43:06.115 32157-571/? D/Q.msg.TroopMsgProxy: insertToList MessageRecord=friendUin:5306senderuin:2361,istroop:1,msgType:-2000,time:1648456985,shmsgseq:867045
2022-03-28 16:43:06.123 32157-571/? D/Q.unread.Proxy_UnreadMonitor: insertOrUpdateUnread update=--ConversationInfo--,shortUin:*5306,type:1,lastread:861312,unreadCount:5721,unreadGiftCount:0,unreadRedPacketCount:0,subAccountTroopunReadMsg:0,PublicAccountConversationRedMask:0,unreadMark:0, extStr:null
2022-03-28 16:43:06.141 32157-32189/? D/ServiceAccountFolderManager: updateServiceAccountBelongInfo(1)->getPublicAccountFolderType->puin:3425372361, folder type:1, no info to judge, default service folder!
2022-03-28 16:43:06.141 32157-32189/? W/JSONParseUtils: error msg in qqpay-api module: org.json.JSONException: No value for gdt_report_list
2022-03-28 16:43:06.396 31924-31924/? W/com.pp51gEC8653: type=1400 audit(0.0:301788): avc: denied { search } for name="bbkcore" dev="sda19" ino=2333 scontext=u:r:untrusted_app:s0:c15,c259,c512,c768 tcontext=u:object_r:vivo_data_file:s0 tclass=dir permissive=0 app=com.pp51gEC8653
2022-03-28 16:43:06.427 31960-31977/? D/ActivityStack: startActivityLocked : ActivityInfo{27685f5 com.icbc.activity.init.NewLoadingActivity}
2022-03-28 16:43:06.428 31924-31924/? I/InputTransport: Create ARC handle: 0xe681fcb0
2022-03-28 16:43:06.430 31960-31977/? D/BProcessManager: init bUid = 10001, bPid = 0
2022-03-28 16:43:06.430 31960-31977/? D/BProcessManager: initProcess: com.icbc
2022-03-28 16:43:06.448 3042-3042/? W/.pp51gEC8653:p: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
2022-03-28 16:43:06.449 1355-1667/? I/ActivityTaskManager: Displayed com.pp51gEC8653/top.niunaijun.blackbox.app.LauncherActivity: +71ms
2022-03-28 16:43:06.452 3042-3042/? E/.pp51gEC8653:p: Not starting debugger since process cannot load the jdwp agent.
2022-03-28 16:43:06.456 31924-2794/? D/InsetsController: default animation onReady types: 1 mShow=true mHasAnimationCallbacks=false mRequestedTypes=1
2022-03-28 16:43:06.489 3042-3042/? I/.pp51gEC8653:p: The ClassLoaderContext is a special shared library.
2022-03-28 16:43:06.515 3042-3042/? D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
2022-03-28 16:43:06.516 3042-3042/? D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
2022-03-28 16:43:06.518 3042-3042/? I/MultiDex: VM with version 2.1.0 has multidex support
2022-03-28 16:43:06.518 3042-3042/? I/MultiDex: Installing application
2022-03-28 16:43:06.518 3042-3042/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2022-03-28 16:43:06.518 3042-3042/? I/MultiDex: Installing application
2022-03-28 16:43:06.518 3042-3042/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2022-03-28 16:43:06.522 3042-3042/? W/.pp51gEC8653:p: Accessing hidden method Ldalvik/system/VMRuntime;->setHiddenApiExemptions([Ljava/lang/String;)V (blacklist,core-platform-api, reflection, denied)
2022-03-28 16:43:06.523 3042-3042/? W/BootstrapClass: reflect bootstrap failed:
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29)
        at me.weishu.reflection.BootstrapClass.exemptAll(Unknown Source:0)
        at me.weishu.reflection.Reflection.unseal(Reflection.java:34)
        at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:124)
        at zzz.adplatform.framework.ADApplication.attachBaseContext(ADApplication.java:35)
        at android.app.Application.attach(Application.java:368)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1209)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1256)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7199)
        at android.app.ActivityThread.access$1500(ActivityThread.java:269)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
     Caused by: java.lang.NoSuchMethodException: dalvik.system.VMRuntime.setHiddenApiExemptions [class [Ljava.lang.String;]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.reflect.Method.invoke(Native Method) 
        at me.weishu.reflection.BootstrapClass.<clinit>(BootstrapClass.java:29) 
        at me.weishu.reflection.BootstrapClass.exemptAll(Unknown Source:0) 
        at me.weishu.reflection.Reflection.unseal(Reflection.java:34) 
        at top.niunaijun.blackbox.BlackBoxCore.doAttachBaseContext(BlackBoxCore.java:124) 
        at zzz.adplatform.framework.ADApplication.attachBaseContext(ADApplication.java:35) 
        at android.app.Application.attach(Application.java:368) 
        at android.app.Instrumentation.newApplication(Instrumentation.java:1209) 
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1256) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7199) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:269) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.app.ActivityThread.main(ActivityThread.java:8228) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016) 
2022-03-28 16:43:06.524 3042-3042/? W/.pp51gEC8653:p: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
2022-03-28 16:43:06.525 3042-3042/? W/.pp51gEC8653:p: DexFile /data/user/0/com.pp51gEC8653/code_cache/1648456986523.dex is in boot class path but is not in a known location
2022-03-28 16:43:06.552 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPermissionManagerProxy@6eb6ee1
2022-03-28 16:43:06.558 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IShortcutManagerProxy@d0b428c
2022-03-28 16:43:06.561 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IActivityManagerProxy@17513b7
2022-03-28 16:43:06.572 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.ILauncherAppsProxy@6c33645
2022-03-28 16:43:06.574 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IDisplayManagerProxy@9d6ed66
2022-03-28 16:43:06.576 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAppOpsManagerProxy@5ac433e
2022-03-28 16:43:06.579 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPackageManagerProxy@56b7c16
2022-03-28 16:43:06.586 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.INotificationManagerProxy@1e10b6d
2022-03-28 16:43:06.590 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.HCallbackProxy@3be47f0
2022-03-28 16:43:06.592 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IWindowManagerProxy@b57f31c
2022-03-28 16:43:06.598 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IMediaSessionManagerProxy@4033687
2022-03-28 16:43:06.601 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAutofillManagerProxy@1ab8d20
2022-03-28 16:43:06.602 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPhoneSubInfoProxy@45c3795
2022-03-28 16:43:06.604 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.ITelephonyManagerProxy@8c9e038
2022-03-28 16:43:06.613 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.INetworkManagementServiceProxy@80cc44d
2022-03-28 16:43:06.616 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IStorageStatsManagerProxy@358054e
2022-03-28 16:43:06.618 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IWifiManagerProxy@b2fca8b
2022-03-28 16:43:06.624 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAppWidgetManagerProxy@36ff214
2022-03-28 16:43:06.627 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IContextHubServiceProxy@600e5b9
2022-03-28 16:43:06.628 3042-3042/? D/HookManager: hook error: top.niunaijun.blackbox.fake.service.IContextHubServiceProxy@600e5b9
2022-03-28 16:43:06.628 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPersistentDataBlockServiceProxy@9af6fac
2022-03-28 16:43:06.629 3042-3042/? D/HookManager: hook error: top.niunaijun.blackbox.fake.service.IPersistentDataBlockServiceProxy@9af6fac
2022-03-28 16:43:06.629 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.context.ContentServiceStub@d0c6c7b
2022-03-28 16:43:06.636 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAccessibilityManagerProxy@a7e0844
2022-03-28 16:43:06.638 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.delegate.AppInstrumentation@1e5984f
2022-03-28 16:43:06.639 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IStorageManagerProxy@f441bdc
2022-03-28 16:43:06.642 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.ILocationManagerProxy@2171a61
2022-03-28 16:43:06.645 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAccountManagerProxy@e982812
2022-03-28 16:43:06.650 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IGraphicsStatsProxy@c83333f
2022-03-28 16:43:06.651 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IPowerManagerProxy@ef684f8
2022-03-28 16:43:06.652 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IDevicePolicyManagerProxy@bc6060d
2022-03-28 16:43:06.661 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.context.RestrictionsManagerStub@abab00e
2022-03-28 16:43:06.663 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IMediaRouterServiceProxy@787a4b
2022-03-28 16:43:06.665 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IConnectivityManagerProxy@eefd2d4
2022-03-28 16:43:06.668 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IAlarmManagerProxy@36f7379
2022-03-28 16:43:06.669 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.libcore.OsStub@9cc22ca
2022-03-28 16:43:06.673 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IJobServiceProxy@a8718b1
2022-03-28 16:43:06.674 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.ITelephonyRegistryProxy@11e4122
2022-03-28 16:43:06.677 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IVibratorServiceProxy@93ac0f
2022-03-28 16:43:06.679 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IActivityTaskManagerProxy@3adce88
2022-03-28 16:43:06.685 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IDeviceIdentifiersPolicyProxy@d5e6a0
2022-03-28 16:43:06.687 3042-3042/? D/HookManager: hook: top.niunaijun.blackbox.fake.service.IUserManagerProxy@41f8b15
2022-03-28 16:43:06.704 31960-31977/? D/ActivityStack: ActivityInfo{27685f5 com.icbc.activity.init.NewLoadingActivity}, windowIsTranslucent: false
2022-03-28 16:43:06.734 31924-2794/? D/InsetsAnimationCtrlImpl: notify control request finished for types: 1
2022-03-28 16:43:06.735 31924-2794/? D/InsetsController: onAnimationFinish showOnFinish: true mRequestedTypes=1
2022-03-28 16:43:06.736 3042-3099/? D/Linux: [Posix_connect Debug]Process com.pp51gEC8653:p0 :443 
2022-03-28 16:43:06.751 3042-3042/? D/NativeCore: NativeCore init.
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：canonicalize0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：getLastModifiedTime0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：setPermission0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：createFileExclusively0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：list0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：createDirectory0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：setLastModifiedTime0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：setReadOnly0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/io/UnixFileSystem, method：getSpace0 success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：java/lang/VMClassLoader, method：findLoadedClass success!
2022-03-28 16:43:06.763 3042-3042/? D/NativeCore: register class：android/os/Binder, method：getCallingUid success!
2022-03-28 16:43:06.766 3042-3042/? I/.pp51gEC8653:p: The ClassLoaderContext is a special shared library.
2022-03-28 16:43:06.853 3042-3099/? D/ad framework initSdk: Success
2022-03-28 16:43:06.853 3042-3099/? E/ad framework init: BD
2022-03-28 16:43:06.860 3042-3042/? W/.pp51gEC8653:p: JIT profile information will not be recorded: profile file does not exist.
2022-03-28 16:43:06.861 3042-3099/? E/ad framework end init: BD
2022-03-28 16:43:06.862 3042-3042/? D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
2022-03-28 16:43:06.862 3042-3099/? I/System.out: line 1: {cd:2022-03-28,ps:[TT]}
2022-03-28 16:43:06.862 3042-3042/? D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: false
2022-03-28 16:43:06.863 3042-3042/? D/NativeCore: set hideXposed
2022-03-28 16:43:06.867 3042-3099/? I/Zeus/init: ZeusManager init, context = zzz.adplatform.framework.ADApplication@9003733, hParam = com.bytedance.pangle.GlobalParam@a5b3af0
2022-03-28 16:43:06.895 3042-3122/? I/TetheringManager: registerTetheringEventCallback:com.pp51gEC8653
2022-03-28 16:43:06.899 3042-3042/? A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 3042 (com.icbc), pid 3042 (com.icbc)
    
    --------- beginning of system
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: Softversion: PD1936D_A_9.16.10
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: Time: 2022-03-28 16:43:06
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: Build fingerprint: 'vivo/PD1936/PD1936:11/RP1A.200720.012/compiler0223171348:user/release-keys'
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: Revision: '0'
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: ABI: 'arm'
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: Timestamp: 2022-03-28 16:43:06+0800
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: pid: 3042, tid: 3042, name: com.icbc  >>> com.icbc <<<
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: uid: 10783
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG: Cause: null pointer dereference
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG:     r0  c017b580  r1  00000000  r2  003a0a5c  r3  00000000
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG:     r4  242baf84  r5  00000000  r6  f39fb5a0  r7  f39fb5a0
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG:     r8  00000000  r9  f39c4e00  r10 ff822380  r11 f39c4e00
2022-03-28 16:43:06.945 3154-3154/? A/DEBUG:     ip  f0c55da8  sp  ff8220e4  lr  c0b9f64f  pc  f0bfb2e6
2022-03-28 16:43:06.948 3154-3154/? A/DEBUG: backtrace:
2022-03-28 16:43:06.948 3154-3154/? A/DEBUG:     NOTE: Function names and BuildId information is missing for some frames due
2022-03-28 16:43:06.948 3154-3154/? A/DEBUG:     NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
2022-03-28 16:43:06.948 3154-3154/? A/DEBUG:     NOTE: found under the lib/ directory are readable.
2022-03-28 16:43:06.948 3154-3154/? A/DEBUG:       #00 pc 000622e6  /apex/com.android.runtime/lib/bionic/libc.so!libc.so (offset 0x2e000) (__memcpy_base_aligned_a9+62) (BuildId: 74d1c33cfa9ab6662e75e1b9e551bd1b)
2022-03-28 16:43:06.948 3154-3154/? A/DEBUG:       #01 pc 0001964b  /data/data/com.pp51gEC8653/blackbox/data/app/com.icbc/lib/libDexHelper.so
2022-03-28 16:43:07.282 26827-27687/? I/cr.sandbox: BrowserIOThread heartbeat, interval/index: 30s/45, render: -1(INVALID), gpu: 1(IN_PROCESS)
2022-03-28 16:43:07.342 31960-31977/? D/BProcessManager: App Died: com.icbc
2022-03-28 16:43:07.343 31960-31977/? I/Process: Sending signal. PID: 3042 SIG: 9
2022-03-28 16:43:07.351 31960-31960/? I/ActivityThread: Removing dead content provider:android.content.ContentProviderProxy@a487b92
2022-03-28 16:43:07.463 31924-31924/? I/InputTransport: Destroy ARC handle: 0xf39c1eb0
2022-03-28 16:43:08.139 31924-31924/? I/InputTransport: Destroy ARC handle: 0xe681fcb0
2022-03-28 16:43:09.033 1355-3482/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-28 16:43:09.095 1355-6777/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-28 16:43:09.160 1355-5699/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2718, arg4: 677, name: com.vivo.fingerprintui
2022-03-28 16:43:09.165 1355-2560/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2718, arg4: 677, name: com.vivo.fingerprintui
2022-03-28 16:43:09.175 1355-1701/? E/BatteryStatsService: Unable to load Power Hal or power.stats HAL
2022-03-28 16:43:09.227 1355-2560/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-28 16:43:09.341 1355-3299/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-28 16:43:09.365 1355-2532/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: -2, arg2: -1, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-28 16:43:09.620 32132-32132/? D/StandbyModeManager: onReceive action: android.intent.action.SCREEN_OFF
2022-03-28 16:43:09.620 32132-32132/? D/StandbyModeManager: stop try start standby by mobileOff ON when screenoff
2022-03-28 16:43:09.623 32157-32157/? D/TESDownloadManager: AppSystemReceiver onReceive
2022-03-28 16:43:09.623 32157-32157/? D/TESDownloadManager: action:android.intent.action.SCREEN_OFF
2022-03-28 16:43:09.625 32132-32132/? D/MSF.C.LogManager: onReceive broadcastreceiver.action = android.intent.action.SCREEN_OFF
2022-03-28 16:43:09.648 32157-32157/? D/Wadl_GameCenterReceiver: onReceive action=android.intent.action.SCREEN_OFF
2022-03-28 16:43:09.649 32157-3392/? D/Wadl_QQGameConfigServiceImpl: checkConfigUpdate isForce=false,newVersion=-1,currVersion=37
2022-03-28 16:43:09.684 26827-27060/? D/StatsFetcherImpl29: foreWifiTxBytes:0k, foreOtherTxBytes:0k,  backWifiTxBytes:0k,  backOtherRxBytes:0k,  foreWifiRxBytes:0k,  foreOtherRxBytes:0k,  backWifiRxBytes:0k,  backOtherTxBytes:0K;
2022-03-28 16:43:09.770 31924-31924/? I/Zeus/receiver: action[android.intent.action.SCREEN_OFF] match success ！ invoke onReceiver
2022-03-28 16:43:09.774 31960-31960/? I/Zeus/receiver: action[android.intent.action.SCREEN_OFF] match success ！ invoke onReceiver
2022-03-28 16:43:09.776 589-589/? I/Zeus/receiver: action[android.intent.action.SCREEN_OFF] match success ！ invoke onReceiver

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by FBlackBox** [comment]
请添加APK文件
