### ISSUE TITLE
Reflector.java line 199 top.niunaijun.blackbox.utils.Reflector.callByCaller (Redmi Note 9 Pro Max android version 11)

### ISSUE THREAD

**Issue by bascobasco** [FBlackBox/BlackBox#7]
Caused by android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.snap.com/... flg=0x10000000 pkg=com.snapchat.android (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2075)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1731)
       at java.lang.reflect.Method.invoke(Method.java)
       at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:199)
       at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.execStartActivity(BaseInstrumentationDelegate.java:353)
       at android.app.Activity.startActivityForResult(Activity.java:5405)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(:10)
       at android.app.Activity.startActivityForResult(Activity.java:5363)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(:10)
       at android.app.Activity.startActivity(Activity.java:5749)
       at android.app.Activity.startActivity(Activity.java:5702)
       at APe.q(:29)
       at m52.onClick(SourceFile:2)
       at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:232)
       at android.widget.TextView.onTouchEvent(TextView.java:10981)
       at android.view.View.dispatchTouchEvent(View.java:14429)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3140)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2819)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:508)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1875)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4210)
       at com.snap.mushroom.MainActivity.dispatchTouchEvent(SourceFile:4)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:466)
       at android.view.View.dispatchPointerEvent(View.java:14690)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6175)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5975)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5464)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5521)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5487)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5639)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5495)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5696)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5468)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5521)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5487)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5495)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5468)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8271)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8222)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8182)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8399)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:283)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:7861)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

Fatal Exception: pb0: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException on scheduler CrashReporting.CrashManagerImpl tid=2 
       at ARc.uncaughtException(SourceFile:1)
       at ARc.uncaughtException(SourceFile:9)
       at Igg.uncaughtException(:22)
       at Up3.c(:23)
       at HR2.b(SourceFile:2)
       at nS2.b(SourceFile:2)
       at GR2.b(SourceFile:2)
       at lS2.b(:18)
       at kS2.h0(SourceFile:20)
       at ER2.c(SourceFile:4)
       at HR2.b(SourceFile:2)
       at lS2.b(:18)
       at kS2.h0(SourceFile:20)
       at ER2.c(SourceFile:4)
       at FR2.h0(SourceFile:4)
       at ER2.c(SourceFile:4)
       at nS2.run(SourceFile:2)
       at Xvd.run(:9)
       at vs5.run(:10)
       at xs5.run(:37)
       at yb0.run(SourceFile:2)
       at X49.run(SourceFile:3)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at RH.run(SourceFile:3)

**Comment by FBlackBox** [comment]
After testing, there is no problem. Please try to compile and run with the latest code

**Comment by bascobasco** [comment]
I think this has to do something with the lack of a web view (or browser inside blackbox)that is just my guess at the moment.
(as this line suggest Intent { act=android.intent.action.VIEW dat=https://www.snap.com/... )

**Comment by FBlackBox** [comment]
Are you using the latest code?

**Comment by FBlackBox** [comment]
May have fixed the problem，see https://github.com/FBlackBox/BlackBox/commit/8a008193bd891fb7f879dce421e34d211ffea261

**Comment by bascobasco** [comment]
This is an issue one of our tester got .It was tag 1.4.2. .Let me inform you if it ever appear again after testing with the new code

**Comment by bascobasco** [comment]
Unfortunately this issue is appearing in more devices  .It has appeared in more than 7 devices now.With the latest code.




Caused by java.lang.Exception: Oops!
       at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:201)
       at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.execStartActivity(BaseInstrumentationDelegate.java:348)
       at android.app.Activity.startActivityForResult(Activity.java:4586)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
       at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
       at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:796)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
       at com.facebook.login.NativeAppLoginMethodHandler.tryIntent(NativeAppLoginMethodHandler.java:151)
       at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:67)
       at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:280)
       at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:233)
       at com.facebook.login.LoginClient.authorize(LoginClient.java:120)
       at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:101)
       at com.facebook.login.LoginFragment.onResume(LoginFragment.java:161)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
       at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
       at android.app.Activity.performResume(Activity.java:7317)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3846)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3888)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1843)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

The new error logs are:
Caused by android.content.ActivityNotFoundException: Unable to find explicit activity class {com.facebook.katana/com.facebook.katana.ProxyAuth}; have you declared this activity in your AndroidManifest.xml?
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2005)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
       at java.lang.reflect.Method.invoke(Method.java)
       at top.niunaijun.blackbox.utils.Reflector.callByCaller(Reflector.java:199)
       at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.execStartActivity(BaseInstrumentationDelegate.java:348)
       at android.app.Activity.startActivityForResult(Activity.java:4586)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
       at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
       at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:796)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:933)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1206)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1194)
       at com.facebook.login.NativeAppLoginMethodHandler.tryIntent(NativeAppLoginMethodHandler.java:151)
       at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:67)
       at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:280)
       at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:233)
       at com.facebook.login.LoginClient.authorize(LoginClient.java:120)
       at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:101)
       at com.facebook.login.LoginFragment.onResume(LoginFragment.java:161)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
       at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
       at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
       at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
       at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
       at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
       at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
       at android.app.Activity.performResume(Activity.java:7317)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3846)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3888)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1843)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6758)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

**Comment by FBlackBox** [comment]
Please provide APK file and explain which step caused this problem
