### ISSUE TITLE
OPPO / Android 7.1.2 /API 25 闪退

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#73]
**Describe the bug** / **描述一下这个错误**
OPPO / Android 7.1.2 /API 25

**To Reproduce** / **复现步骤**

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
OPPO / Android 7.1.2 /API 25

**Logcat** / **日志**
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb D/BProcessManager: App Died: com.jrummyapps.rootchecker
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb W/System.err: java.lang.Exception: call killProcess callstack! pid=7364
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb W/System.err:     at android.os.Process.killProcess(Process.java:1168)
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb W/System.err:     at top.niunaijun.blackbox.core.system.ProcessRecord.kill(ProcessRecord.java:63)
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb W/System.err:     at top.niunaijun.blackbox.core.system.BProcessManagerService.onProcessDie(BProcessManagerService.java:202)
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb W/System.err:     at top.niunaijun.blackbox.core.system.BProcessManagerService$1.binderDied(BProcessManagerService.java:185)
2022-03-29 10:08:23.935 6959-6971/com.hffbedhfb W/System.err:     at android.os.BinderProxy.sendDeathNotice(Binder.java:688)

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by asdwyujian** [comment]
[com.jrummyapps.rootchecker.zip](https://github.com/FBlackBox/BlackBox/files/8369611/com.jrummyapps.rootchecker.zip)
