### ISSUE TITLE
samsung galaxy s7 /android 6.0.1 / api 23 闪退

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#76]
**Describe the bug** / **描述一下这个错误**
samsung galaxy s7 /android 6.0.1 / api 23 闪退

**To Reproduce** / **复现步骤**

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
samsung galaxy s7 /android 6.0.1 / api 23

**Logcat** / **日志**
2022-03-29 10:31:24.081 485-497/? W/SettingsProvider: call() with invalid method: 
2022-03-29 10:31:24.086 3133-3133/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at com.unicom.shield.UnicomApplicationWrapper.onCreate(UnicomApplicationWrapper.java:46)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at com.yodo1.android.sdk.cu.Yodo1Application.onCreate(Yodo1Application.java:30)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:370)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:290)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:89)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at android.os.Looper.loop(Looper.java:148)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5654)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:759)
2022-03-29 10:31:24.086 3133-3133/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
2022-03-29 10:31:24.086 3133-3133/? D/AndroidRuntime: Shutting down VM
2022-03-29 10:31:24.098 3133-3133/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yodo1tier1.SD999.timetravel, PID: 3133
    java.lang.RuntimeException: Unable to makeApplication
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:376)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:290)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:89)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5654)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:759)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
        at com.unicom.shield.UnicomApplicationWrapper.onCreate(UnicomApplicationWrapper.java:46)
        at com.yodo1.android.sdk.cu.Yodo1Application.onCreate(Yodo1Application.java:30)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:370)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:290) 
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168) 
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:89) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5654) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:759) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by asdwyujian** [comment]
BlackBox-Canary-v28，解决
