### ISSUE TITLE
BlackReflection.java line 56 top.niunaijun.blackreflection.BlackReflection.create.

### ISSUE THREAD

**Issue by bascobasco** [FBlackBox/BlackBox#8]
On two devices we are getting the error below:
The devices are:
Redmi 6A  (Android 9)

Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.fragment.app.n
       at android.os.Parcel.readParcelableCreator(Parcel.java:2847)
       at android.os.Parcel.readParcelable(Parcel.java:2768)
       at android.os.Parcel.readValue(Parcel.java:2671)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3045)
       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
       at android.os.BaseBundle.size(BaseBundle.java:359)
       at android.app.servertransaction.LaunchActivityItem.hashCode(LaunchActivityItem.java:193)
       at java.util.AbstractList.hashCode(AbstractList.java:541)
       at java.util.Objects.hashCode(Objects.java:98)
       at android.app.servertransaction.ClientTransaction.hashCode(ClientTransaction.java:236)
       at java.util.WeakHashMap.hash(WeakHashMap.java:298)
       at java.util.WeakHashMap.get(WeakHashMap.java:396)
       at top.niunaijun.blackreflection.BlackReflection.create(BlackReflection.java:56)
       at black.android.app.servertransaction.BRClientTransaction.get(BRClientTransaction.java:21)
       at top.niunaijun.blackbox.fake.service.HCallbackProxy.getLaunchActivityItem(HCallbackProxy.java:110)
       at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:124)
       at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6820)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922

**Comment by nnjun** [comment]
Does it happen every time, or occasionally?

**Comment by bascobasco** [comment]
So far it has only happened on two devices both of them Redmi.

**Comment by bascobasco** [comment]
And on all of the it happens occasionally

**Comment by FBlackBox** [comment]
Fixed https://github.com/FBlackBox/BlackBox/commit/675fbb0352d18101b769d74da66cf16b355cc76d

Try it
