### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by liuyueban9** [FBlackBox/BlackBox#81]
**Describe the bug** / **app闪退**
app闪退。

**To Reproduce** / **复现步骤**

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
vivo/ Android11

**Logcat** / **日志**
2022-03-29 12:55:57.191 1537-1537/? I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
2022-03-29 12:55:57.194 1537-1537/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at com.unicom.shield.UnicomApplicationWrapper.onCreate(UnicomApplicationWrapper.java:46)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at com.yodo1.android.sdk.cu.Yodo1Application.onCreate(Yodo1Application.java:30)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1242)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:370)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:290)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at android.os.Looper.loop(Looper.java:257)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8228)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
2022-03-29 12:55:57.194 1537-1537/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
2022-03-29 12:55:57.197 1537-1537/? D/AndroidRuntime: Shutting down VM
2022-03-29 12:55:57.198 1537-1537/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yodo1tier1.SD999.timetravel, PID: 1537
    java.lang.RuntimeException: Unable to makeApplication
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:376)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:290)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168)
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8228)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
        at com.unicom.shield.UnicomApplicationWrapper.onCreate(UnicomApplicationWrapper.java:46)
        at com.yodo1.android.sdk.cu.Yodo1Application.onCreate(Yodo1Application.java:30)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1242)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callApplicationOnCreate(BaseInstrumentationDelegate.java:225)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:140)
        at top.niunaijun.blackbox.app.BActivityThread.handleBindApplication(BActivityThread.java:370)
        at top.niunaijun.blackbox.app.BActivityThread.bindApplication(BActivityThread.java:290) 
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleLaunchActivity(HCallbackProxy.java:168) 
        at top.niunaijun.blackbox.fake.service.HCallbackProxy.handleMessage(HCallbackProxy.java:82) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:257) 
        at android.app.ActivityThread.main(ActivityThread.java:8228) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1016) 
2022-03-29 12:55:57.201 1537-1537/? W/D999.timetravel: type=1400 audit(0.0:561210): avc: denied { nlmsg_readpriv } for scontext=u:r:untrusted_app:s0:c56,c259,c512,c768 tcontext=u:r:untrusted_app:s0:c56,c259,c512,c768 tclass=netlink_route_socket permissive=0 b/155595000 app=com.dgaecdejc
2022-03-29 12:55:57.201 1537-1537/? W/D999.timetravel: type=1400 audit(0.0:561211): avc: denied { nlmsg_readpriv } for scontext=u:r:untrusted_app:s0:c56,c259,c512,c768 tcontext=u:r:untrusted_app:s0:c56,c259,c512,c768 tclass=netlink_route_socket permissive=0 b/155595000 app=com.dgaecdejc
2022-03-29 12:55:57.241 1537-1537/? I/Process: Sending signal. PID: 1537 SIG: 9
2022-03-29 12:55:57.267 32672-32725/? D/BProcessManager: App Died: com.yodo1tier1.SD999.timetravel
2022-03-29 12:55:57.267 32672-32725/? I/Process: Sending signal. PID: 1537 SIG: 9
2022-03-29 12:55:57.340 28761-28761/? I/awcn.AppLifeCycle:  onTrimMemory level:5
2022-03-29 12:55:57.616 4308-8294/? W/MessengerIpcClient: Timing out request: 1
2022-03-29 12:55:57.648 4308-8732/? W/GLSUser: [AppCertManager] Failed to get security token.
    java.io.IOException: SERVICE_NOT_AVAILABLE
        at aazt.b(:com.google.android.gms@201817057@20.18.17 (140408-311416286):19)
        at aazt.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):18)
        at aazt.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):11)
        at htb.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):16)
        at hsz.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):41)
        at hsu.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):0)
        at hsx.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):10)
        at fye.call(:com.google.android.gms@201817057@20.18.17 (140408-311416286):5)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at qiw.b(:com.google.android.gms@201817057@20.18.17 (140408-311416286):12)
        at qiw.run(:com.google.android.gms@201817057@20.18.17 (140408-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at qow.run(:com.google.android.gms@201817057@20.18.17 (140408-311416286):0)
        at java.lang.Thread.run(Thread.java:923)
2022-03-29 12:55:57.717 4308-8732/? D/Linux: [Posix_connect Debug]Process com.google.android.gms.persistent :443 
2022-03-29 12:55:57.769 4308-8732/? W/Conscrypt: Could not set socket write timeout: java.net.SocketException: Socket closed
2022-03-29 12:55:57.769 4308-8732/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.Platform.setSocketWriteTimeout(:com.google.android.gms@201817057@20.18.17 (140408-311416286):2)
2022-03-29 12:55:57.769 4308-8732/? W/Conscrypt:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.setSoWriteTimeout(:com.google.android.gms@201817057@20.18.17 (140408-311416286):0)
2022-03-29 12:55:57.806 4308-8732/? V/NativeCrypto: SSL handshake aborted: ssl=0xb4000078d79ba808: I/O error during system call, Connection reset by peer
2022-03-29 12:55:57.807 4308-8732/? W/GLSUser: [AppCertManager] IOException while requesting key: 
    javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xb4000078d79ba808: I/O error during system call, Connection reset by peer
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@201817057@20.18.17 (140408-311416286):6)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@201817057@20.18.17 (140408-311416286):16)
        at anuq.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):22)
        at anuq.createSocket(:com.google.android.gms@201817057@20.18.17 (140408-311416286):9)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:185)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at zlc.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):30)
        at ixi.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):5)
        at fzn.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):9)
        at fzn.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):5)
        at htb.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):31)
        at hsz.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):41)
        at hsu.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):0)
        at hsx.a(:com.google.android.gms@201817057@20.18.17 (140408-311416286):10)
        at fye.call(:com.google.android.gms@201817057@20.18.17 (140408-311416286):5)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at qiw.b(:com.google.android.gms@201817057@20.18.17 (140408-311416286):12)
        at qiw.run(:com.google.android.gms@201817057@20.18.17 (140408-311416286):7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at qow.run(:com.google.android.gms@201817057@20.18.17 (140408-311416286):0)
        at java.lang.Thread.run(Thread.java:923)
2022-03-29 12:55:57.997 1355-3289/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-29 12:55:57.999 1355-3289/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-29 12:55:58.001 1355-3289/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: -2, arg2: -1, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-29 12:55:58.044 1355-3289/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 1080, arg2: 2340, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-29 12:55:58.062 32634-32634/? I/InputTransport: Destroy ARC handle: 0xb778fcc0
2022-03-29 12:55:58.083 32634-32634/? I/InputTransport: Destroy ARC handle: 0xf1a58070
2022-03-29 12:55:58.655 22115-22505/? I/SmartThreadExecutor: handleMessage: start check 0
2022-03-29 12:55:58.659 22115-22505/? I/SmartThreadExecutor: handleMessage: check end 0 -34 false
2022-03-29 12:55:58.665 4308-4308/? W/MessengerIpcClient: Received response for unknown request: 1
2022-03-29 12:55:59.043 17059-17174/? D/MemoryCeilingMonitor: [handleMemoryCalculate]
2022-03-29 12:55:59.044 17059-17174/? D/MemoryCeilingMonitor: [calculate] tot: 7497704, max: 268435456, free: 3277120, heap: 4220584, per: 0.01572290062904358
2022-03-29 12:56:00.005 22115-22115/? D/TESDownloadManager: AppSystemReceiver onReceive
2022-03-29 12:56:00.005 22115-22115/? D/TESDownloadManager: action:android.intent.action.TIME_TICK
2022-03-29 12:56:02.023 5116-1816/? I/Authzen: [DeviceStateSyncManager] The server is in sync with current state. Nothing to do
2022-03-29 12:56:02.420 17059-17266/? D/MSF.C.CodecWarppertrue: recv Packet ssoSeq:-401593430, uin:*7940
2022-03-29 12:56:02.421 17059-17266/? D/MSF.C.NetConnTag.true: netRecv ssoSeq:-401593430 uin:*7940 cmd:BS08PTQ9FS85K34EOAgwKSIEIjsvKAgpLQ -401592830 cross:0 socketEngineID: 0 socket: 250593610
2022-03-29 12:56:02.429 17059-17255/? I/MSF.S.AppProcessManager: SendToApp PUSH process:com.tencent.mobileqq fromServiceMsg: FromServiceMsg msName:onRecvPushMsg ssoSeq:-401593430 serviceCmd:OnlinePush.PbPushGroupMsg appSeq:-401593430 failCode:1000 cost = 0 needBoot=true from.len = 505
2022-03-29 12:56:02.430 17059-17266/? D/MSF.C.CodecWarppertrue: recv Packet ssoSeq:-393980283, uin:*7940
2022-03-29 12:56:02.431 17059-17266/? D/MSF.C.NetConnTag.true: netRecv ssoSeq:-393980283 uin:*7940 cmd:BS08PTQ9FS85K34EOAgwKSIEIjsvKAgpLQ -393979851 cross:0 socketEngineID: 0 socket: 250593610
2022-03-29 12:56:02.435 22115-22133/? D/MSF.D.Proxy: onRecvServicePushResp, fromServiceMsg cmd = OnlinePush.PbPushGroupMsg, ssoSeq = -401593430, length = 505
2022-03-29 12:56:02.436 17059-17255/? I/MSF.S.AppProcessManager: SendToApp PUSH process:com.tencent.mobileqq fromServiceMsg: FromServiceMsg msName:onRecvPushMsg ssoSeq:-393980283 serviceCmd:OnlinePush.PbPushGroupMsg appSeq:-393980283 failCode:1000 cost = 0 needBoot=true from.len = 334
2022-03-29 12:56:02.438 22115-22133/? D/MSF.D.Proxy: onRecvServicePushResp, fromServiceMsg cmd = OnlinePush.PbPushGroupMsg, ssoSeq = -393980283, length = 334
2022-03-29 12:56:02.497 22115-22243/? I/troop_ext: onTroopReceiveOrSendMsg troopInfo is null or not eliminated. troopUin: 6465306
2022-03-29 12:56:02.506 22115-22243/? E/MessagePBElemDecoder: parseCommentReferSeq  mRootMsgSeq:868500 mReferMsgSeq:868506
2022-03-29 12:56:02.548 22115-22243/? D/Q.msg.TroopMsgProxy: insertToList MessageRecord=friendUin:5306senderuin:6190,istroop:1,msgType:-1049,time:1648529762,shmsgseq:868519
2022-03-29 12:56:02.556 22115-22243/? D/Q.unread.Proxy_UnreadMonitor: insertOrUpdateUnread update=--ConversationInfo--,shortUin:*5306,type:1,lastread:861312,unreadCount:7207,unreadGiftCount:0,unreadRedPacketCount:0,subAccountTroopunReadMsg:0,PublicAccountConversationRedMask:0,unreadMark:0, extStr:null
2022-03-29 12:56:02.573 22115-22145/? D/ServiceAccountFolderManager: updateServiceAccountBelongInfo(1)->getPublicAccountFolderType->puin:2557976190, folder type:1, no info to judge, default service folder!
2022-03-29 12:56:02.576 22115-22145/? W/JSONParseUtils: error msg in qqpay-api module: org.json.JSONException: No value for gdt_report_list
2022-03-29 12:56:02.577 22115-22243/? I/troop_ext: onTroopReceiveOrSendMsg troopInfo is null or not eliminated. troopUin: 6465306
2022-03-29 12:56:02.596 22115-22243/? D/Q.msg.TroopMsgProxy: insertToList MessageRecord=friendUin:5306senderuin:3270,istroop:1,msgType:-1000,time:1648529762,shmsgseq:868520
2022-03-29 12:56:02.600 22115-22243/? D/Q.unread.Proxy_UnreadMonitor: insertOrUpdateUnread update=--ConversationInfo--,shortUin:*5306,type:1,lastread:861312,unreadCount:7208,unreadGiftCount:0,unreadRedPacketCount:0,subAccountTroopunReadMsg:0,PublicAccountConversationRedMask:0,unreadMark:0, extStr:null
2022-03-29 12:56:02.636 22115-22145/? D/ServiceAccountFolderManager: updateServiceAccountBelongInfo(1)->getPublicAccountFolderType->puin:164333270, folder type:1, no info to judge, default service folder!
2022-03-29 12:56:02.636 22115-22145/? W/JSONParseUtils: error msg in qqpay-api module: org.json.JSONException: No value for gdt_report_list
2022-03-29 12:56:02.776 32634-32648/? W/System: A resource failed to call dispose. 
2022-03-29 12:56:04.094 1355-1509/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: -2, arg2: -1, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-29 12:56:04.109 1355-3482/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: -2, arg2: -1, arg3: 2524, arg4: 468, name: com.android.systemui
2022-03-29 12:56:06.260 29039-30382/? W/SQLiteLog: (28) double-quoted string literal: "networkPrefer"
2022-03-29 12:56:06.260 29039-30382/? W/SQLiteLog: (28) double-quoted string literal: "session"
2022-03-29 12:56:08.085 28761-28761/? I/awcn.AppLifeCycle:  onTrimMemory level:5
2022-03-29 12:56:08.123 28321-28355/? I/AdrenoGLES-0: QUALCOMM build                   : e1ac91e, I2b3b5fbd00
    Build Date                       : 11/17/20
    OpenGL ES Shader Compiler Version: EV************
    Local Branch                     : mybrancheb28e622-fc96-f136-8e55-5cb90179c3d8
    Remote Branch                    : quic/gfx-adreno.lnx.1.0.r99-rel
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2022-03-29 12:56:08.124 28321-28355/? I/AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
2022-03-29 12:56:08.124 28321-28355/? I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
2022-03-29 12:56:08.149 28321-28355/? I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
2022-03-29 12:56:10.543 28761-30030/? I/cr.sandbox: BrowserIOThread heartbeat, interval/index: 30s/3, render: -1(INVALID), gpu: 1(IN_PROCESS)
2022-03-29 12:56:14.863 17059-17194/? D/WorkerThreadMonitor: Kill MSF check result[ senderSize:0,sendInterval:39272,receiveInterval=12432,addCmdCount=465
2022-03-29 12:56:17.517 4308-4323/? I/.gms.persisten: Background concurrent copying GC freed 138493(12MB) AllocSpace objects, 8(356KB) LOS objects, 64% free, 6641KB/18MB, paused 67us total 148.140ms
2022-03-29 12:56:18.114 32072-32290/? W/id.AlipayGphon: Unsupported class loader
2022-03-29 12:56:18.121 32072-32290/? W/id.AlipayGphon: Unsupported class loader
2022-03-29 12:56:18.201 32072-32072/? W/SGBackgroud: type=1400 audit(0.0:561218): avc: granted { execute } for path="/data/user/0/com.eg.android.AlipayGphone/app_SGLib/app_1647679983/main/libsgsecuritybodyso-6.5.15408830.so" dev="sda19" ino=2443809 scontext=u:r:untrusted_app_29:s0:c24,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c24,c257,c512,c768 tclass=file app=com.eg.android.AlipayGphone
2022-03-29 12:56:18.326 32072-32285/? W/id.AlipayGphon: Class com.alibaba.one.android.inner.BroadcastReceiverJniBridge failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
2022-03-29 12:56:18.401 32072-32290/? W/id.AlipayGphon: Unsupported class loader
2022-03-29 12:56:18.479 32072-32290/? W/id.AlipayGphon: Unsupported class loader
2022-03-29 12:56:18.571 32072-32072/? W/SGBackgroud: type=1400 audit(0.0:561219): avc: granted { execute } for path="/data/user/0/com.eg.android.AlipayGphone/app_SGLib/app_1647679983/main/libsgmiddletierso-6.5.15106478.so" dev="sda19" ino=1983928 scontext=u:r:untrusted_app_29:s0:c24,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c24,c257,c512,c768 tclass=file app=com.eg.android.AlipayGphone
2022-03-29 12:56:21.242 32634-2442/? D/Linux: [Posix_connect Debug]Process com.dgaecdejc :443 
2022-03-29 12:56:23.403 32072-32283/? I/ValarMorghulis: __1551
2022-03-29 12:56:23.774 17059-17174/? D/MSF.C.DeepSleepDetector: [run] count after++: 61
2022-03-29 12:56:26.051 28761-28761/? W/CrashSDKBkgdHan: type=1400 audit(0.0:561272): avc: denied { read } for name="loadavg" dev="proc" ino=4026532124 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:proc_loadavg:s0 tclass=file permissive=0 app=com.alibaba.android.rimet
2022-03-29 12:56:26.735 22115-22115/? D/TESDownloadManager: AppSystemReceiver onReceive
2022-03-29 12:56:26.735 22115-22115/? D/TESDownloadManager: action:android.intent.action.BATTERY_CHANGED
2022-03-29 12:56:26.735 32634-32634/? I/Zeus/receiver: action[android.intent.action.BATTERY_CHANGED] match success ！ invoke onReceiver
2022-03-29 12:56:26.736 32634-32634/? I/Zeus/receiver: action[android.intent.action.BATTERY_CHANGED] match success ！ invoke onReceiver
2022-03-29 12:56:26.836 5116-30887/? D/Linux: [Posix_connect Debug]Process com.google.android.gms :443 
2022-03-29 12:56:27.796 32634-365/? I/TeaLog: p worked:true 9223370388324988012
2022-03-29 12:56:27.819 32634-365/? I/TeaLog: s0 0
2022-03-29 12:56:27.819 32634-365/? I/TeaLog: s worked:true 9223370388324987988
2022-03-29 12:56:28.728 22115-22505/? I/SmartThreadExecutor: handleMessage: start check 0
2022-03-29 12:56:28.728 22115-22505/? I/SmartThreadExecutor: handleMessage: check end 0 -35 false
2022-03-29 12:56:29.053 17059-17174/? D/MemoryCeilingMonitor: [handleMemoryCalculate]
2022-03-29 12:56:29.054 17059-17174/? D/MemoryCeilingMonitor: [calculate] tot: 7497704, max: 268435456, free: 3178816, heap: 4318888, per: 0.01608911156654358
2022-03-29 12:56:30.464 22115-22115/? D/TESDownloadManager: AppSystemReceiver onReceive
2022-03-29 12:56:30.464 22115-22115/? D/TESDownloadManager: action:android.intent.action.BATTERY_CHANGED
2022-03-29 12:56:30.473 32634-32634/? I/Zeus/receiver: action[android.intent.action.BATTERY_CHANGED] match success ！ invoke onReceiver
2022-03-29 12:56:30.473 32634-32634/? I/Zeus/receiver: action[android.intent.action.BATTERY_CHANGED] match success ！ invoke onReceiver
2022-03-29 12:56:37.754 28761-28761/? I/cr.gpuproc: [gpu_client_impl.cc(0x78d673b030,45) GpuClientImpl] client_id: 4
2022-03-29 12:56:37.760 28761-28761/? I/cr.ucmedia: [media_service_impl.cc(50) MediaServiceImpl] 0x78d6894280[1/1], web_contents_: 0x781c544bd0
2022-03-29 12:56:37.771 28761-29026/? W/MessageQueue: Handler (android.os.Handler) {851c291} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {851c291} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:564)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.post(Handler.java:427)
        at android.app.LoadedApk$ReceiverDispatcher.performReceive(LoadedApk.java:1724)
        at android.app.LoadedApk$ReceiverDispatcher$InnerReceiver.performReceive(LoadedApk.java:1495)
        at android.app.ActivityThread$ApplicationThread.scheduleRegisteredReceiver(ActivityThread.java:1363)
        at android.app.IApplicationThread$Stub.onTransact(IApplicationThread.java:907)
        at android.app.ActivityThread$ApplicationThread.onTransact(ActivityThread.java:1992)
        at android.os.Binder.execTransactInternal(Binder.java:1159)
        at android.os.Binder.execTransact(Binder.java:1123)
2022-03-29 12:56:37.780 28761-30174/? W/MessageQueue: Handler (android.os.Handler) {851c291} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {851c291} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:564)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.post(Handler.java:427)
        at org.chromium.net.NetworkChangeNotifierAutoDetect.a(PG:823)
        at org.chromium.net.NetworkChangeNotifierAutoDetect.a(PG:54)
        at org.chromium.net.NetworkChangeNotifierAutoDetect$b.onAvailable(PG:566)
        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3451)
        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3736)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-03-29 12:56:37.781 28761-30174/? W/MessageQueue: Handler (android.os.Handler) {851c291} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {851c291} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:564)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.post(Handler.java:427)
        at org.chromium.net.NetworkChangeNotifierAutoDetect.a(PG:823)
        at org.chromium.net.NetworkChangeNotifierAutoDetect.a(PG:54)
        at org.chromium.net.NetworkChangeNotifierAutoDetect$b.onCapabilitiesChanged(PG:590)
        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3456)
        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3736)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2022-03-29 12:56:37.921 4308-29066/? D/Linux: [Posix_connect Debug]Process com.google.android.gms.persistent :443 
2022-03-29 12:56:39.012 17059-17215/? W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
2022-03-29 12:56:40.089 32634-334/? I/Zeus/receiver: ZeusTransformUtils-registerReceiver-execute
2022-03-29 12:56:40.090 32634-334/? I/Zeus/receiver: ZeusTransformUtils-registerReceiver-execute
2022-03-29 12:56:40.255 32634-365/? I/TeaLog: p worked:true 60000
2022-03-29 12:56:40.261 32634-365/? I/TeaLog: s0 0
2022-03-29 12:56:40.261 32634-365/? I/TeaLog: s worked:true 60000
2022-03-29 12:56:40.553 28761-30030/? I/cr.sandbox: BrowserIOThread heartbeat, interval/index: 30s/4, render: -1(INVALID), gpu: 1(IN_PROCESS)
2022-03-29 12:56:44.217 27338-29415/? I/mars::stn: [longlink_connect_monitor.cc:470, OnHeartbeatAlarmSet]:longlink_progress on_heartbeat_set, time: 100915247, time interval:210000
2022-03-29 12:56:46.801 1355-3485/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 70, arg2: 70, arg3: 2510, arg4: 1, name: com.bbk.facewake
2022-03-29 12:56:46.831 22752-2509/? E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2022-03-29 12:56:46.832 1355-3485/? D/BatteryStatsService: notePemString  noteWhich: 49,arg1: 70, arg2: 70, arg3: 2510, arg4: 1, name: com.bbk.facewake
2022-03-29 12:56:46.821 22752-22752/? W/Binder:22752_B: type=1400 audit(0.0:561275): avc: denied { read } for name="u:object_r:vendor_persist_camera_prop:s0" dev="tmpfs" ino=8122 scontext=u:r:untrusted_app_29:s0:c167,c256,c512,c768 tcontext=u:object_r:vendor_persist_camera_prop:s0 tclass=file permissive=0 app=com.tencent.mm
2022-03-29 12:56:48.597 5116-2616/? I/GmscoreIpa: Starting mediastore instant index

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by FBlackBox** [comment]
请添加APK文件
