### ISSUE TITLE
猎豹清理大师已停止运行 android 7

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#82]
**Describe the bug** / **描述一下这个错误**
BlackBox-Canary-v28
闪退。

**To Reproduce** / **复现步骤**
手动安装apk后，点击图标进入。

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
samsung SM-N976N / android 9 / api 28

**Logcat** / **日志**
2022-03-29 19:42:50.226 1266-2054/system_process W/ActivityManager:   Force finishing activity com.eegcibbcf/top.niunaijun.blackbox.app.LauncherActivity
2022-03-29 19:42:50.255 1266-1281/system_process W/System.err: java.lang.Exception: show AlertDialog! title=猎豹清理大师已停止运行
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at android.app.AlertDialog.show(AlertDialog.java:134)
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at com.android.server.am.AppErrors.handleShowAppErrorUi(AppErrors.java:719)
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1637)
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at android.os.Looper.loop(Looper.java:154)
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
2022-03-29 19:42:50.323 1266-1281/system_process W/System.err:     at com.android.server.ServiceThread.run(ServiceThread.java:46)
2022-03-29 19:42:50.542 1266-2734/system_process I/HostConnection: HostConnection::HostConnection: pid=1266, tid=2734, this=0xa5e146c0

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

**Comment by FBlackBox** [comment]
该问题不处理。
