### ISSUE TITLE
BlackBox-CanaryV28 的 requestInstallPackage没起作用

### ISSUE THREAD

**Issue by asdwyujian** [FBlackBox/BlackBox#84]
**Describe the bug** / **描述一下这个错误**
BlackBox-CanaryV28 的 requestInstallPackage没起作用，

**To Reproduce** / **复现步骤**
1.手动安装apk，点击图标进入到apk，
2.apk程序提示需要自动更新，点击更新。
3.程序自动下载升级，点击安装，就提示“安装失败 ”

**Expected behavior** / **预期的行为**
以前都是安装成功的。

   public boolean requestInstallPackage(File file){
                    BlackBoxCore.get().installPackageAsUser(file, 0);
                    return true;
                }

**Screenshots** / **截图**
![Screenshot_20220330-120344](https://user-images.githubusercontent.com/41764372/160749242-b22bddcc-c137-43c1-ba6f-3d063f5afbe2.png)

**Mobile Phone Info** / **手机信息**
OPPO / android 7 

**Logcat** / **日志**
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err: java.lang.Exception: Toast callstack! strTip=貌似安装失败，请手动更新
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.widget.Toast.show(Toast.java:130)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at com.github.ss.game.base.BaseFragment.toast(BaseFragment.kt:33)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at com.github.ss.game.ui.HomeFragment$downHandler$1$handleMessage$1.onClick(HomeFragment.kt:624)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.view.View.performClick(View.java:5637)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.os.Looper.loop(Looper.java:154)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6190)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
2022-03-30 12:09:42.650 14088-14088/com.mogu.go W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2022-03-30 12:09:42.651 1079-1183/? D/audio_hw_hal: raw_start_output_stream, stream=0xc6f05140, sampleRate=48000, channel=2, bps=16, bufSize=4096

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
有。

[蘑菇加速器0.95.zip](https://github.com/FBlackBox/BlackBox/files/8376950/0.95.zip)

**Comment by FBlackBox** [comment]
app自身问题，原版也是一样。
