### ISSUE TITLE
android 9 安装本地游戏apk 报错

### ISSUE THREAD

**Issue by liuyusheng1228** [FBlackBox/BlackBox#93]
Process: com.jyjs, PID: 8386
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jyjs/demo.MainActivity}: java.lang.RuntimeException: java.util.NoSuchElementException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
     Caused by: java.lang.RuntimeException: java.util.NoSuchElementException
        at com.supersdk.presenter.SuperHelper.activity_creat(SuperHelper.java:258)
        at demo.MainActivity.onCreate(MainActivity.java:107)
        at android.app.Activity.performCreate(Activity.java:7146)
        at android.app.Activity.performCreate(Activity.java:7137)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861) 
     Caused by: java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:863)
        at com.qipa.floatutil.StudyFloatUtilManager.doStartApplicationWithPackageName(StudyFloatUtilManager.java:81)
        at com.qipa.floatutil.StudyFloatUtilManager.init(StudyFloatUtilManager.java:54)
        at com.supersdk.presenter.SuperHelper.creat_game(SuperHelper.java:350)
        at com.supersdk.presenter.SuperHelper.activity_creat(SuperHelper.java:253)
        at demo.MainActivity.onCreate(MainActivity.java:107) 
        at android.app.Activity.performCreate(Activity.java:7146) 
        at android.app.Activity.performCreate(Activity.java:7137) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240) 
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861) 
2022-04-07 20:23:11.188 8386-8510/com.jyjs E/JIGUANG-JCore: [ReportUtils] wrap data failed

**Comment by FBlackBox** [comment]
这个不是安装出错吧？

**Comment by liuyusheng1228** [comment]
不是安装出错，是打开app的时候报的错

**Comment by liuyusheng1228** [comment]
> 这个不是安装出错吧？

不是安装出错，是打开app的时候报的错

**Comment by liuyusheng1228** [comment]
> 这个不是安装出错吧？

谢谢你的回复，不是安装出错，是打开app的时候报的错

**Comment by FBlackBox** [comment]
> > 这个不是安装出错吧？
> 
> 谢谢你的回复，不是安装出错，是打开app的时候报的错

提供一下你的应用。

**Comment by liuyusheng1228** [comment]
> > > 这个不是安装出错吧？
> > 
> > 
> > 谢谢你的回复，不是安装出错，是打开app的时候报的错
> 
> 提供一下你的应用。

好的 ，谢谢 https://github.com/liuyusheng1228/NewQipaProject/releases/download/ces/jyjs7pa4.62022225.apk

**Comment by liuyusheng1228** [comment]
你好，大佬，我请教一下，这个游戏 我如果本地安装了，然后再到黑盒里面安装是可以打开的，如果本地没安装就会报错，我想问一下是不是安装哪里少了文件，还是我们hook的时候是不是因为hook不到啊   

Process: com.jyjs, PID: 13813
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jyjs/demo.MainActivity}: java.lang.RuntimeException: java.util.NoSuchElementException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
     Caused by: java.lang.RuntimeException: java.util.NoSuchElementException
        at com.supersdk.presenter.SuperHelper.activity_creat(SuperHelper.java:258)
        at demo.MainActivity.onCreate(MainActivity.java:107)
        at android.app.Activity.performCreate(Activity.java:7146)
        at android.app.Activity.performCreate(Activity.java:7137)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240)
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861) 
     Caused by: java.util.NoSuchElementException
        at java.util.ArrayList$Itr.next(ArrayList.java:863)
        at com.qipa.floatutil.StudyFloatUtilManager.doStartApplicationWithPackageName(StudyFloatUtilManager.java:81)
        at com.qipa.floatutil.StudyFloatUtilManager.init(StudyFloatUtilManager.java:54)
        at com.supersdk.presenter.SuperHelper.creat_game(SuperHelper.java:350)
        at com.supersdk.presenter.SuperHelper.activity_creat(SuperHelper.java:253)
        at demo.MainActivity.onCreate(MainActivity.java:107) 
        at android.app.Activity.performCreate(Activity.java:7146) 
        at android.app.Activity.performCreate(Activity.java:7137) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240) 
        at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)

**Comment by liuyusheng1228** [comment]
> > > 这个不是安装出错吧？
> > 
> > 
> > 谢谢你的回复，不是安装出错，是打开app的时候报的错
> 
> 提供一下你的应用。
你好，大佬，我请教一下，这个游戏 我如果本地安装了，然后再到黑盒里面安装是可以打开的，如果本地没安装就会报错，我想问一下是不是安装哪里少了文件，还是我们hook的时候是不是因为hook不到啊

Process: com.jyjs, PID: 13813
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jyjs/demo.MainActivity}: java.lang.RuntimeException: java.util.NoSuchElementException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6669)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
Caused by: java.lang.RuntimeException: java.util.NoSuchElementException
at com.supersdk.presenter.SuperHelper.activity_creat(SuperHelper.java:258)
at demo.MainActivity.onCreate(MainActivity.java:107)
at android.app.Activity.performCreate(Activity.java:7146)
at android.app.Activity.performCreate(Activity.java:7137)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240)
at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:193) 
at android.app.ActivityThread.main(ActivityThread.java:6669) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861) 
Caused by: java.util.NoSuchElementException
at java.util.ArrayList$Itr.next(ArrayList.java:863)
at com.qipa.floatutil.StudyFloatUtilManager.doStartApplicationWithPackageName(StudyFloatUtilManager.java:81)
at com.qipa.floatutil.StudyFloatUtilManager.init(StudyFloatUtilManager.java:54)
at com.supersdk.presenter.SuperHelper.creat_game(SuperHelper.java:350)
at com.supersdk.presenter.SuperHelper.activity_creat(SuperHelper.java:253)
at demo.MainActivity.onCreate(MainActivity.java:107) 
at android.app.Activity.performCreate(Activity.java:7146) 
at android.app.Activity.performCreate(Activity.java:7137) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
at top.niunaijun.blackbox.fake.delegate.BaseInstrumentationDelegate.callActivityOnCreate(BaseInstrumentationDelegate.java:240) 
at top.niunaijun.blackbox.fake.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:134) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loop(Looper.java:193) 
at android.app.ActivityThread.main(ActivityThread.java:6669) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:533) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
